// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `categories` resource.

#[derive(Clone)]
pub struct CategoriesResource {
    client: crate::client::ProfoundClient,
}

impl CategoriesResource {
    pub(crate) fn new(client: crate::client::ProfoundClient) -> Self {
        Self { client }
    }

    /// Get Categories
    pub fn list(&self) -> ListRequestBuilder {
        ListRequestBuilder::new(self.client.clone())
    }

    /// Get Category Topics
    pub fn topics(&self, category_id: impl Into<String>) -> TopicsRequestBuilder {
        TopicsRequestBuilder::new(self.client.clone(), category_id.into())
    }

    /// Get Category Tags
    pub fn tags(&self, category_id: impl Into<String>) -> TagsRequestBuilder {
        TagsRequestBuilder::new(self.client.clone(), category_id.into())
    }

    /// List prompts
    pub fn prompts(&self, category_id: impl Into<String>) -> PromptsRequestBuilder {
        PromptsRequestBuilder::new(self.client.clone(), category_id.into())
    }

    /// Get Category Assets
    pub fn assets(&self, category_id: impl Into<String>) -> AssetsRequestBuilder {
        AssetsRequestBuilder::new(self.client.clone(), category_id.into())
    }

    /// Get Category Personas
    pub fn get_category_personas(&self, category_id: impl Into<String>) -> GetCategoryPersonasRequestBuilder {
        GetCategoryPersonasRequestBuilder::new(self.client.clone(), category_id.into())
    }

    /// Create prompts
    pub fn create_prompts(
        &self,
        category_id: impl Into<String>,
        body: crate::models::CreatePromptsBody,
    ) -> CreatePromptsRequestBuilder {
        CreatePromptsRequestBuilder::new(self.client.clone(), category_id.into(), body)
    }

    /// Update prompts
    pub fn update_prompts(
        &self,
        category_id: impl Into<String>,
        body: crate::models::UpdatePromptsBody,
    ) -> UpdatePromptsRequestBuilder {
        UpdatePromptsRequestBuilder::new(self.client.clone(), category_id.into(), body)
    }

    /// Update prompt status
    pub fn update_prompt_status(
        &self,
        category_id: impl Into<String>,
        body: crate::models::UpdatePromptStatusBody,
    ) -> UpdatePromptStatusRequestBuilder {
        UpdatePromptStatusRequestBuilder::new(self.client.clone(), category_id.into(), body)
    }

    /// Get Category Regions
    pub fn retrieve_regions(&self, category_id: impl Into<String>) -> RetrieveRegionsRequestBuilder {
        RetrieveRegionsRequestBuilder::new(self.client.clone(), category_id.into())
    }

    /// Get Category Citation Categories
    pub fn get_citation_categories(&self, category_id: impl Into<String>) -> GetCitationCategoriesRequestBuilder {
        GetCitationCategoriesRequestBuilder::new(self.client.clone(), category_id.into())
    }
}

/// Get the organization categories, one row per (category, organization) pair.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListRequestBuilder {
    client: crate::client::ProfoundClient,
    organization_ids: Option<Vec<String>>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListRequestBuilder {
    fn new(client: crate::client::ProfoundClient) -> Self {
        Self {
            client,
            organization_ids: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Restrict results to one or more organizations the caller belongs to. Repeat the parameter to target multiple orgs (e.g. `?organization_ids=<id1>&organization_ids=<id2>`). Omit to return data from every organization the caller has access to.
    pub fn organization_ids(mut self, value: Vec<String>) -> Self {
        self.organization_ids = Some(value);
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Vec<crate::models::CategoryWithOrganization>, crate::error::Error> {
        let path = "/v1/org/categories".to_string();
        let mut query: Vec<(String, String)> = Vec::new();
        if let Some(values) = &self.organization_ids {
            for item in values {
                query.push(("organization_ids".to_string(), crate::http::scalar_value(item)));
            }
        }
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Vec<crate::models::CategoryWithOrganization>, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Get the topics for a specific category.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct TopicsRequestBuilder {
    client: crate::client::ProfoundClient,
    category_id: String,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl TopicsRequestBuilder {
    fn new(client: crate::client::ProfoundClient, category_id: String) -> Self {
        Self {
            client,
            category_id,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Vec<crate::models::Topic>, crate::error::Error> {
        let path = format!(
            "/v1/org/categories/{}/topics",
            crate::http::encode_path_param(&self.category_id)
        );
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Vec<crate::models::Topic>, _>(http::Method::GET, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Get the tags for a specific category.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct TagsRequestBuilder {
    client: crate::client::ProfoundClient,
    category_id: String,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl TagsRequestBuilder {
    fn new(client: crate::client::ProfoundClient, category_id: String) -> Self {
        Self {
            client,
            category_id,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Vec<crate::models::Tag>, crate::error::Error> {
        let path = format!(
            "/v1/org/categories/{}/tags",
            crate::http::encode_path_param(&self.category_id)
        );
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Vec<crate::models::Tag>, _>(http::Method::GET, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Retrieve prompts in a category with optional filtering by type, topic, tag, region, platform, or persona. Supports cursor-based pagination.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct PromptsRequestBuilder {
    client: crate::client::ProfoundClient,
    category_id: String,
    limit: Option<i64>,
    cursor: Option<String>,
    order_by: Option<crate::models::PromptOrderBy>,
    order_dir: Option<crate::models::OrderByDirection>,
    analysis_type: Option<Vec<crate::models::AnalysisType>>,
    prompt_type: Option<Vec<crate::models::PromptType>>,
    status: Option<Vec<String>>,
    topic_id: Option<Vec<String>>,
    tag_id: Option<Vec<String>>,
    region_id: Option<Vec<String>>,
    platform_id: Option<Vec<String>>,
    persona_id: Option<Vec<String>>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl PromptsRequestBuilder {
    fn new(client: crate::client::ProfoundClient, category_id: String) -> Self {
        Self {
            client,
            category_id,
            limit: None,
            cursor: None,
            order_by: None,
            order_dir: None,
            analysis_type: None,
            prompt_type: None,
            status: None,
            topic_id: None,
            tag_id: None,
            region_id: None,
            platform_id: None,
            persona_id: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Maximum number of prompts to return.
    pub fn limit(mut self, value: i64) -> Self {
        self.limit = Some(value);
        self
    }

    /// Pagination cursor from a previous response.
    pub fn cursor(mut self, value: impl Into<String>) -> Self {
        self.cursor = Some(value.into());
        self
    }

    /// Field used to order prompts.
    pub fn order_by(mut self, value: crate::models::PromptOrderBy) -> Self {
        self.order_by = Some(value);
        self
    }

    /// Sort direction for the selected order field.
    pub fn order_dir(mut self, value: crate::models::OrderByDirection) -> Self {
        self.order_dir = Some(value);
        self
    }

    /// Filter by analysis type (visibility, sentiment, accuracy).
    pub fn analysis_type(mut self, value: Vec<crate::models::AnalysisType>) -> Self {
        self.analysis_type = Some(value);
        self
    }

    /// Deprecated. Use analysis_type instead.
    pub fn prompt_type(mut self, value: Vec<crate::models::PromptType>) -> Self {
        self.prompt_type = Some(value);
        self
    }

    /// Filter by prompt status. Defaults to `active` only.
    pub fn status(mut self, value: Vec<String>) -> Self {
        self.status = Some(value);
        self
    }

    /// Filter by topic IDs.
    pub fn topic_id(mut self, value: Vec<String>) -> Self {
        self.topic_id = Some(value);
        self
    }

    /// Filter by tag IDs.
    pub fn tag_id(mut self, value: Vec<String>) -> Self {
        self.tag_id = Some(value);
        self
    }

    /// Filter by region IDs.
    pub fn region_id(mut self, value: Vec<String>) -> Self {
        self.region_id = Some(value);
        self
    }

    /// Filter by platform IDs.
    pub fn platform_id(mut self, value: Vec<String>) -> Self {
        self.platform_id = Some(value);
        self
    }

    /// Filter by persona IDs.
    pub fn persona_id(mut self, value: Vec<String>) -> Self {
        self.persona_id = Some(value);
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::CategoryPromptsResponse, crate::error::Error> {
        let path = format!(
            "/v1/org/categories/{}/prompts",
            crate::http::encode_path_param(&self.category_id)
        );
        let mut query: Vec<(String, String)> = Vec::new();
        if let Some(value) = &self.limit {
            query.push(("limit".to_string(), crate::http::scalar_value(value)));
        }
        if let Some(value) = &self.cursor {
            query.push(("cursor".to_string(), crate::http::scalar_value(value)));
        }
        if let Some(value) = &self.order_by {
            query.push(("order_by".to_string(), crate::http::scalar_value(value)));
        }
        if let Some(value) = &self.order_dir {
            query.push(("order_dir".to_string(), crate::http::scalar_value(value)));
        }
        if let Some(values) = &self.analysis_type {
            for item in values {
                query.push(("analysis_type".to_string(), crate::http::scalar_value(item)));
            }
        }
        if let Some(values) = &self.prompt_type {
            for item in values {
                query.push(("prompt_type".to_string(), crate::http::scalar_value(item)));
            }
        }
        if let Some(values) = &self.status {
            for item in values {
                query.push(("status".to_string(), crate::http::scalar_value(item)));
            }
        }
        if let Some(values) = &self.topic_id {
            for item in values {
                query.push(("topic_id".to_string(), crate::http::scalar_value(item)));
            }
        }
        if let Some(values) = &self.tag_id {
            for item in values {
                query.push(("tag_id".to_string(), crate::http::scalar_value(item)));
            }
        }
        if let Some(values) = &self.region_id {
            for item in values {
                query.push(("region_id".to_string(), crate::http::scalar_value(item)));
            }
        }
        if let Some(values) = &self.platform_id {
            for item in values {
                query.push(("platform_id".to_string(), crate::http::scalar_value(item)));
            }
        }
        if let Some(values) = &self.persona_id {
            for item in values {
                query.push(("persona_id".to_string(), crate::http::scalar_value(item)));
            }
        }
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::CategoryPromptsResponse, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Get Category Assets
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct AssetsRequestBuilder {
    client: crate::client::ProfoundClient,
    category_id: String,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl AssetsRequestBuilder {
    fn new(client: crate::client::ProfoundClient, category_id: String) -> Self {
        Self {
            client,
            category_id,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Vec<crate::models::CategoryAsset>, crate::error::Error> {
        let path = format!(
            "/v1/org/categories/{}/assets",
            crate::http::encode_path_param(&self.category_id)
        );
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Vec<crate::models::CategoryAsset>, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Get Category Personas
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct GetCategoryPersonasRequestBuilder {
    client: crate::client::ProfoundClient,
    category_id: String,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl GetCategoryPersonasRequestBuilder {
    fn new(client: crate::client::ProfoundClient, category_id: String) -> Self {
        Self {
            client,
            category_id,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::CategoryPersonasResponse, crate::error::Error> {
        let path = format!(
            "/v1/org/categories/{}/personas",
            crate::http::encode_path_param(&self.category_id)
        );
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::CategoryPersonasResponse, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Create one or more prompts in a category. Topics and tags are auto-created if referenced by name and not yet existing. Use dry_run to preview without persisting.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreatePromptsRequestBuilder {
    client: crate::client::ProfoundClient,
    category_id: String,
    body: crate::models::CreatePromptsBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl CreatePromptsRequestBuilder {
    fn new(client: crate::client::ProfoundClient, category_id: String, body: crate::models::CreatePromptsBody) -> Self {
        Self {
            client,
            category_id,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::CreatePromptsResponse, crate::error::Error> {
        let path = format!(
            "/v1/org/categories/{}/prompts",
            crate::http::encode_path_param(&self.category_id)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::CreatePromptsResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Update one or more existing prompts. Only provided fields are changed. Dimension fields (regions, platforms, personas, tags) replace the full set when provided. Use dry_run to preview without persisting.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UpdatePromptsRequestBuilder {
    client: crate::client::ProfoundClient,
    category_id: String,
    body: crate::models::UpdatePromptsBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl UpdatePromptsRequestBuilder {
    fn new(client: crate::client::ProfoundClient, category_id: String, body: crate::models::UpdatePromptsBody) -> Self {
        Self {
            client,
            category_id,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::UpdatePromptsResponse, crate::error::Error> {
        let path = format!(
            "/v1/org/categories/{}/prompts",
            crate::http::encode_path_param(&self.category_id)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::UpdatePromptsResponse, _>(
                http::Method::PATCH,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Bulk-update the status of one or more prompts. Prompts already in the target status are skipped. Use dry_run to preview without persisting.
///
/// Status options:
/// - 'active': Prompts will run daily.
/// - 'disabled': Prompts will not run moving forward, but historical data is preserved.
/// - 'deleted': Prompts are deleted along with historical data
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UpdatePromptStatusRequestBuilder {
    client: crate::client::ProfoundClient,
    category_id: String,
    body: crate::models::UpdatePromptStatusBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl UpdatePromptStatusRequestBuilder {
    fn new(
        client: crate::client::ProfoundClient,
        category_id: String,
        body: crate::models::UpdatePromptStatusBody,
    ) -> Self {
        Self {
            client,
            category_id,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::UpdatePromptStatusResponse, crate::error::Error> {
        let path = format!(
            "/v1/org/categories/{}/prompts/status",
            crate::http::encode_path_param(&self.category_id)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::UpdatePromptStatusResponse, _>(
                http::Method::PATCH,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Get the regions for a specific category.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct RetrieveRegionsRequestBuilder {
    client: crate::client::ProfoundClient,
    category_id: String,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl RetrieveRegionsRequestBuilder {
    fn new(client: crate::client::ProfoundClient, category_id: String) -> Self {
        Self {
            client,
            category_id,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Vec<crate::models::NamedResource>, crate::error::Error> {
        let path = format!(
            "/v1/org/categories/{}/regions",
            crate::http::encode_path_param(&self.category_id)
        );
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Vec<crate::models::NamedResource>, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Get the citation categories for a category: the built-in buckets plus any custom categories.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct GetCitationCategoriesRequestBuilder {
    client: crate::client::ProfoundClient,
    category_id: String,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl GetCitationCategoriesRequestBuilder {
    fn new(client: crate::client::ProfoundClient, category_id: String) -> Self {
        Self {
            client,
            category_id,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::CitationCategoriesResponse, crate::error::Error> {
        let path = format!(
            "/v1/org/categories/{}/citation-categories",
            crate::http::encode_path_param(&self.category_id)
        );
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::CitationCategoriesResponse, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
