// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `knowledgeBases` resource.

#[derive(Clone)]
pub struct KnowledgeBasesResource {
    client: crate::client::ProfoundClient,
}

impl KnowledgeBasesResource {
    pub(crate) fn new(client: crate::client::ProfoundClient) -> Self {
        Self { client }
    }

    /// List Knowledge Bases
    pub fn list(&self) -> ListRequestBuilder {
        ListRequestBuilder::new(self.client.clone())
    }

    /// Search Knowledge Base
    pub fn search(
        &self,
        knowledge_base_id: impl Into<String>,
        body: crate::models::SearchKnowledgeBaseRequest,
    ) -> SearchRequestBuilder {
        SearchRequestBuilder::new(self.client.clone(), knowledge_base_id.into(), body)
    }

    pub fn documents(&self) -> crate::resources::knowledge_bases_documents::KnowledgeBasesDocumentsResource {
        crate::resources::knowledge_bases_documents::KnowledgeBasesDocumentsResource::new(self.client.clone())
    }

    pub fn folders(&self) -> crate::resources::folders::FoldersResource {
        crate::resources::folders::FoldersResource::new(self.client.clone())
    }
}

/// List knowledge bases accessible to the API key.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListRequestBuilder {
    client: crate::client::ProfoundClient,
    organization_id: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListRequestBuilder {
    fn new(client: crate::client::ProfoundClient) -> Self {
        Self {
            client,
            organization_id: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Organization scope for API keys that can access multiple organizations.
    pub fn organization_id(mut self, value: impl Into<String>) -> Self {
        self.organization_id = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ListKnowledgeBasesResponse, crate::error::Error> {
        let path = "/v1/knowledge-bases".to_string();
        let mut query: Vec<(String, String)> = Vec::new();
        if let Some(value) = &self.organization_id {
            query.push(("organization_id".to_string(), crate::http::scalar_value(value)));
        }
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ListKnowledgeBasesResponse, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Search a knowledge base and return matching snippets or pages.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct SearchRequestBuilder {
    client: crate::client::ProfoundClient,
    knowledge_base_id: String,
    body: crate::models::SearchKnowledgeBaseRequest,
    organization_id: Option<String>,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl SearchRequestBuilder {
    fn new(
        client: crate::client::ProfoundClient,
        knowledge_base_id: String,
        body: crate::models::SearchKnowledgeBaseRequest,
    ) -> Self {
        Self {
            client,
            knowledge_base_id,
            body,
            organization_id: None,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Organization scope for API keys that can access multiple organizations.
    pub fn organization_id(mut self, value: impl Into<String>) -> Self {
        self.organization_id = Some(value.into());
        self
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::KnowledgeBaseSearchResponse, crate::error::Error> {
        let path = format!(
            "/v1/knowledge-bases/{}/search",
            crate::http::encode_path_param(&self.knowledge_base_id)
        );
        let mut query: Vec<(String, String)> = Vec::new();
        if let Some(value) = &self.organization_id {
            query.push(("organization_id".to_string(), crate::http::scalar_value(value)));
        }
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::KnowledgeBaseSearchResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
