// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Resource sub-clients and root accessors.

pub mod accuracy;
pub mod ad_account;
pub mod ads;
pub mod agents;
pub mod categories;
pub mod claims;
pub mod content;
pub mod documents;
pub mod factcheck;
pub mod folders;
pub mod generations;
pub mod integrations;
pub mod knowledge_bases;
pub mod knowledge_bases_documents;
pub mod node_types;
pub mod openai_ads;
pub mod optimization;
pub mod organizations;
pub mod projects;
pub mod prompts;
pub mod reports;
pub mod runs;
pub mod shopping;
pub mod social;
pub mod tasks;
pub mod web_search_results;
pub mod youtube;

impl crate::client::ProfoundClient {
    pub fn organizations(&self) -> crate::resources::organizations::OrganizationsResource {
        crate::resources::organizations::OrganizationsResource::new(self.clone())
    }

    pub fn prompts(&self) -> crate::resources::prompts::PromptsResource {
        crate::resources::prompts::PromptsResource::new(self.clone())
    }

    pub fn reports(&self) -> crate::resources::reports::ReportsResource {
        crate::resources::reports::ReportsResource::new(self.clone())
    }

    pub fn content(&self) -> crate::resources::content::ContentResource {
        crate::resources::content::ContentResource::new(self.clone())
    }

    pub fn agents(&self) -> crate::resources::agents::AgentsResource {
        crate::resources::agents::AgentsResource::new(self.clone())
    }

    pub fn knowledge_bases(&self) -> crate::resources::knowledge_bases::KnowledgeBasesResource {
        crate::resources::knowledge_bases::KnowledgeBasesResource::new(self.clone())
    }

    pub fn projects(&self) -> crate::resources::projects::ProjectsResource {
        crate::resources::projects::ProjectsResource::new(self.clone())
    }

    pub fn integrations(&self) -> crate::resources::integrations::IntegrationsResource {
        crate::resources::integrations::IntegrationsResource::new(self.clone())
    }

    pub fn documents(&self) -> crate::resources::documents::DocumentsResource {
        crate::resources::documents::DocumentsResource::new(self.clone())
    }

    pub fn ads(&self) -> crate::resources::ads::AdsResource {
        crate::resources::ads::AdsResource::new(self.clone())
    }
}
