// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `organizations` resource.

#[derive(Clone)]
pub struct OrganizationsResource {
    client: crate::client::ProfoundClient,
}

impl OrganizationsResource {
    pub(crate) fn new(client: crate::client::ProfoundClient) -> Self {
        Self { client }
    }

    /// Get Regions
    pub fn regions(&self) -> RegionsRequestBuilder {
        RegionsRequestBuilder::new(self.client.clone())
    }

    /// Get Models
    pub fn models(&self) -> ModelsRequestBuilder {
        ModelsRequestBuilder::new(self.client.clone())
    }

    /// Get Domains
    pub fn domains(&self) -> DomainsRequestBuilder {
        DomainsRequestBuilder::new(self.client.clone())
    }

    /// Get Assets
    pub fn list_assets(&self) -> ListAssetsRequestBuilder {
        ListAssetsRequestBuilder::new(self.client.clone())
    }

    /// Get Personas
    pub fn get_personas(&self) -> GetPersonasRequestBuilder {
        GetPersonasRequestBuilder::new(self.client.clone())
    }

    /// List organizations
    pub fn list(&self) -> ListRequestBuilder {
        ListRequestBuilder::new(self.client.clone())
    }

    pub fn categories(&self) -> crate::resources::categories::CategoriesResource {
        crate::resources::categories::CategoriesResource::new(self.client.clone())
    }
}

/// Get the organization regions.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct RegionsRequestBuilder {
    client: crate::client::ProfoundClient,
    organization_ids: Option<Vec<String>>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl RegionsRequestBuilder {
    fn new(client: crate::client::ProfoundClient) -> Self {
        Self {
            client,
            organization_ids: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Restrict results to one or more organizations the caller belongs to. Repeat the parameter to target multiple orgs (e.g. `?organization_ids=<id1>&organization_ids=<id2>`). Omit to return data from every organization the caller has access to.
    pub fn organization_ids(mut self, value: Vec<String>) -> Self {
        self.organization_ids = Some(value);
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Vec<crate::models::NamedResource>, crate::error::Error> {
        let path = "/v1/org/regions".to_string();
        let mut query: Vec<(String, String)> = Vec::new();
        if let Some(values) = &self.organization_ids {
            for item in values {
                query.push(("organization_ids".to_string(), crate::http::scalar_value(item)));
            }
        }
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Vec<crate::models::NamedResource>, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Get the organization models.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ModelsRequestBuilder {
    client: crate::client::ProfoundClient,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ModelsRequestBuilder {
    fn new(client: crate::client::ProfoundClient) -> Self {
        Self {
            client,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Vec<crate::models::NamedResource>, crate::error::Error> {
        let path = "/v1/org/models".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Vec<crate::models::NamedResource>, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Get the organization domains.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DomainsRequestBuilder {
    client: crate::client::ProfoundClient,
    organization_ids: Option<Vec<String>>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl DomainsRequestBuilder {
    fn new(client: crate::client::ProfoundClient) -> Self {
        Self {
            client,
            organization_ids: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Restrict results to one or more organizations the caller belongs to. Repeat the parameter to target multiple orgs (e.g. `?organization_ids=<id1>&organization_ids=<id2>`). Omit to return data from every organization the caller has access to.
    pub fn organization_ids(mut self, value: Vec<String>) -> Self {
        self.organization_ids = Some(value);
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Vec<crate::models::DomainWithOrganization>, crate::error::Error> {
        let path = "/v1/org/domains".to_string();
        let mut query: Vec<(String, String)> = Vec::new();
        if let Some(values) = &self.organization_ids {
            for item in values {
                query.push(("organization_ids".to_string(), crate::http::scalar_value(item)));
            }
        }
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Vec<crate::models::DomainWithOrganization>, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Get the organization assets, one row per (asset, organization) pair.
///
/// An asset's category can belong to multiple organizations; one asset row is
/// emitted per owning org so no association is silently dropped.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListAssetsRequestBuilder {
    client: crate::client::ProfoundClient,
    organization_ids: Option<Vec<String>>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListAssetsRequestBuilder {
    fn new(client: crate::client::ProfoundClient) -> Self {
        Self {
            client,
            organization_ids: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Restrict results to one or more organizations the caller belongs to. Repeat the parameter to target multiple orgs (e.g. `?organization_ids=<id1>&organization_ids=<id2>`). Omit to return data from every organization the caller has access to.
    pub fn organization_ids(mut self, value: Vec<String>) -> Self {
        self.organization_ids = Some(value);
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::OrganizationAssetsResponse, crate::error::Error> {
        let path = "/v1/org/assets".to_string();
        let mut query: Vec<(String, String)> = Vec::new();
        if let Some(values) = &self.organization_ids {
            for item in values {
                query.push(("organization_ids".to_string(), crate::http::scalar_value(item)));
            }
        }
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::OrganizationAssetsResponse, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Get the organization personas, one row per (persona, organization) pair.
///
/// Same (item, org) fan-out as ``get_assets``: a persona's category can be
/// owned by multiple orgs, and each owning org gets its own row so no
/// association is silently dropped.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct GetPersonasRequestBuilder {
    client: crate::client::ProfoundClient,
    organization_ids: Option<Vec<String>>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl GetPersonasRequestBuilder {
    fn new(client: crate::client::ProfoundClient) -> Self {
        Self {
            client,
            organization_ids: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Restrict results to one or more organizations the caller belongs to. Repeat the parameter to target multiple orgs (e.g. `?organization_ids=<id1>&organization_ids=<id2>`). Omit to return data from every organization the caller has access to.
    pub fn organization_ids(mut self, value: Vec<String>) -> Self {
        self.organization_ids = Some(value);
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::OrganizationPersonasWithCategoryResponse, crate::error::Error> {
        let path = "/v1/org/personas".to_string();
        let mut query: Vec<(String, String)> = Vec::new();
        if let Some(values) = &self.organization_ids {
            for item in values {
                query.push(("organization_ids".to_string(), crate::http::scalar_value(item)));
            }
        }
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::OrganizationPersonasWithCategoryResponse, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Return every organization the caller's API key grants access to. Use this to discover organization IDs before calling endpoints that accept an `organization_id` filter.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListRequestBuilder {
    client: crate::client::ProfoundClient,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListRequestBuilder {
    fn new(client: crate::client::ProfoundClient) -> Self {
        Self {
            client,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Vec<crate::models::Organization>, crate::error::Error> {
        let path = "/v1/org".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Vec<crate::models::Organization>, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
