// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `projects` resource.

#[derive(Clone)]
pub struct ProjectsResource {
    client: crate::client::ProfoundClient,
}

impl ProjectsResource {
    pub(crate) fn new(client: crate::client::ProfoundClient) -> Self {
        Self { client }
    }

    /// List Projects
    pub fn list(&self, category_id: impl Into<String>) -> ListRequestBuilder {
        ListRequestBuilder::new(self.client.clone(), category_id.into())
    }

    /// Create Project
    pub fn create(&self, body: crate::models::CreateProjectRequest) -> CreateRequestBuilder {
        CreateRequestBuilder::new(self.client.clone(), body)
    }

    /// Get Project
    pub fn retrieve(&self, project_id: impl Into<String>, category_id: impl Into<String>) -> RetrieveRequestBuilder {
        RetrieveRequestBuilder::new(self.client.clone(), project_id.into(), category_id.into())
    }

    /// Delete Project
    pub fn delete(&self, project_id: impl Into<String>, category_id: impl Into<String>) -> DeleteRequestBuilder {
        DeleteRequestBuilder::new(self.client.clone(), project_id.into(), category_id.into())
    }

    /// Get Project Status
    pub fn get_status(&self, project_id: impl Into<String>, category_id: impl Into<String>) -> GetStatusRequestBuilder {
        GetStatusRequestBuilder::new(self.client.clone(), project_id.into(), category_id.into())
    }

    /// Archive Project
    pub fn archive(&self, project_id: impl Into<String>, category_id: impl Into<String>) -> ArchiveRequestBuilder {
        ArchiveRequestBuilder::new(self.client.clone(), project_id.into(), category_id.into())
    }

    /// Unarchive Project
    pub fn unarchive(&self, project_id: impl Into<String>, category_id: impl Into<String>) -> UnarchiveRequestBuilder {
        UnarchiveRequestBuilder::new(self.client.clone(), project_id.into(), category_id.into())
    }

    pub fn generations(&self) -> crate::resources::generations::GenerationsResource {
        crate::resources::generations::GenerationsResource::new(self.client.clone())
    }

    pub fn tasks(&self) -> crate::resources::tasks::TasksResource {
        crate::resources::tasks::TasksResource::new(self.client.clone())
    }
}

/// List Projects
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListRequestBuilder {
    client: crate::client::ProfoundClient,
    category_id: String,
    status: Option<String>,
    limit: Option<i64>,
    offset: Option<i64>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListRequestBuilder {
    fn new(client: crate::client::ProfoundClient, category_id: String) -> Self {
        Self {
            client,
            category_id,
            status: None,
            limit: None,
            offset: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Comma-separated project statuses: suggested, tracked, retired.
    pub fn status(mut self, value: impl Into<String>) -> Self {
        self.status = Some(value.into());
        self
    }

    pub fn limit(mut self, value: i64) -> Self {
        self.limit = Some(value);
        self
    }

    pub fn offset(mut self, value: i64) -> Self {
        self.offset = Some(value);
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ListProjectsResponse, crate::error::Error> {
        let path = "/v1/projects".to_string();
        let mut query: Vec<(String, String)> = Vec::new();
        let value = &self.category_id;
        query.push(("category_id".to_string(), crate::http::scalar_value(value)));
        if let Some(value) = &self.status {
            query.push(("status".to_string(), crate::http::scalar_value(value)));
        }
        if let Some(value) = &self.limit {
            query.push(("limit".to_string(), crate::http::scalar_value(value)));
        }
        if let Some(value) = &self.offset {
            query.push(("offset".to_string(), crate::http::scalar_value(value)));
        }
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ListProjectsResponse, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Create Project
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateRequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::CreateProjectRequest,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl CreateRequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::CreateProjectRequest) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ProjectGenerationResponse, crate::error::Error> {
        let path = "/v1/projects".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ProjectGenerationResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Get Project
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct RetrieveRequestBuilder {
    client: crate::client::ProfoundClient,
    project_id: String,
    category_id: String,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl RetrieveRequestBuilder {
    fn new(client: crate::client::ProfoundClient, project_id: String, category_id: String) -> Self {
        Self {
            client,
            project_id,
            category_id,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ProjectDetailResponse, crate::error::Error> {
        let path = format!("/v1/projects/{}", crate::http::encode_path_param(&self.project_id));
        let mut query: Vec<(String, String)> = Vec::new();
        let value = &self.category_id;
        query.push(("category_id".to_string(), crate::http::scalar_value(value)));
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ProjectDetailResponse, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Delete Project
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DeleteRequestBuilder {
    client: crate::client::ProfoundClient,
    project_id: String,
    category_id: String,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl DeleteRequestBuilder {
    fn new(client: crate::client::ProfoundClient, project_id: String, category_id: String) -> Self {
        Self {
            client,
            project_id,
            category_id,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    pub async fn send(self) -> Result<(), crate::error::Error> {
        let path = format!("/v1/projects/{}", crate::http::encode_path_param(&self.project_id));
        let mut query: Vec<(String, String)> = Vec::new();
        let value = &self.category_id;
        query.push(("category_id".to_string(), crate::http::scalar_value(value)));
        let mut headers: Vec<(String, String)> = vec![("Accept".to_string(), "*/*".to_string())];
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send_empty(http::Method::DELETE, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Get Project Status
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct GetStatusRequestBuilder {
    client: crate::client::ProfoundClient,
    project_id: String,
    category_id: String,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl GetStatusRequestBuilder {
    fn new(client: crate::client::ProfoundClient, project_id: String, category_id: String) -> Self {
        Self {
            client,
            project_id,
            category_id,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ProjectStatusResponse, crate::error::Error> {
        let path = format!(
            "/v1/projects/{}/status",
            crate::http::encode_path_param(&self.project_id)
        );
        let mut query: Vec<(String, String)> = Vec::new();
        let value = &self.category_id;
        query.push(("category_id".to_string(), crate::http::scalar_value(value)));
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ProjectStatusResponse, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Archive Project
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ArchiveRequestBuilder {
    client: crate::client::ProfoundClient,
    project_id: String,
    category_id: String,
    body: Option<crate::models::ArchiveProjectRequest>,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ArchiveRequestBuilder {
    fn new(client: crate::client::ProfoundClient, project_id: String, category_id: String) -> Self {
        Self {
            client,
            project_id,
            category_id,
            body: None,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    pub fn body(mut self, value: crate::models::ArchiveProjectRequest) -> Self {
        self.body = Some(value);
        self
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ProjectResponse, crate::error::Error> {
        let path = format!(
            "/v1/projects/{}/archive",
            crate::http::encode_path_param(&self.project_id)
        );
        let mut query: Vec<(String, String)> = Vec::new();
        let value = &self.category_id;
        query.push(("category_id".to_string(), crate::http::scalar_value(value)));
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = self.body.as_ref();
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ProjectResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Unarchive Project
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UnarchiveRequestBuilder {
    client: crate::client::ProfoundClient,
    project_id: String,
    category_id: String,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl UnarchiveRequestBuilder {
    fn new(client: crate::client::ProfoundClient, project_id: String, category_id: String) -> Self {
        Self {
            client,
            project_id,
            category_id,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ProjectResponse, crate::error::Error> {
        let path = format!(
            "/v1/projects/{}/unarchive",
            crate::http::encode_path_param(&self.project_id)
        );
        let mut query: Vec<(String, String)> = Vec::new();
        let value = &self.category_id;
        query.push(("category_id".to_string(), crate::http::scalar_value(value)));
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ProjectResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
