// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `reports` resource.

#[derive(Clone)]
pub struct ReportsResource {
    client: crate::client::ProfoundClient,
}

impl ReportsResource {
    pub(crate) fn new(client: crate::client::ProfoundClient) -> Self {
        Self { client }
    }

    /// Query Citations
    pub fn citations(&self, body: crate::models::CitationsQuery) -> CitationsRequestBuilder {
        CitationsRequestBuilder::new(self.client.clone(), body)
    }

    /// Query Visibility
    pub fn visibility(&self, body: crate::models::VisibilityQuery) -> VisibilityRequestBuilder {
        VisibilityRequestBuilder::new(self.client.clone(), body)
    }

    /// Query Sentiment
    pub fn sentiment(&self, body: crate::models::SentimentQuery) -> SentimentRequestBuilder {
        SentimentRequestBuilder::new(self.client.clone(), body)
    }

    /// Query Sentiment V2
    pub fn sentiment_v2(&self, body: crate::models::SentimentV2ReportQuery) -> SentimentV2RequestBuilder {
        SentimentV2RequestBuilder::new(self.client.clone(), body)
    }

    /// Get Referrals Report V1
    pub fn get_referrals_report(&self, body: crate::models::ReferralsQuery) -> GetReferralsReportRequestBuilder {
        GetReferralsReportRequestBuilder::new(self.client.clone(), body)
    }

    /// Get Bots Report V1
    pub fn get_bots_report(&self, body: crate::models::BotsReportQuery) -> GetBotsReportRequestBuilder {
        GetBotsReportRequestBuilder::new(self.client.clone(), body)
    }

    /// Query Fanouts
    pub fn query_fanouts(&self, body: crate::models::QueryFanoutsQuery) -> QueryFanoutsRequestBuilder {
        QueryFanoutsRequestBuilder::new(self.client.clone(), body)
    }

    /// Stream Citations
    pub fn stream_citations(&self, body: crate::models::StreamCitationsQuery) -> StreamCitationsRequestBuilder {
        StreamCitationsRequestBuilder::new(self.client.clone(), body)
    }

    /// Stream Visibility
    pub fn stream_visibility(&self, body: crate::models::StreamVisibilityQuery) -> StreamVisibilityRequestBuilder {
        StreamVisibilityRequestBuilder::new(self.client.clone(), body)
    }

    /// Stream Sentiment
    pub fn stream_sentiment(&self, body: crate::models::StreamSentimentQuery) -> StreamSentimentRequestBuilder {
        StreamSentimentRequestBuilder::new(self.client.clone(), body)
    }

    /// Stream Citations V2
    pub fn stream_citations_v2(&self, body: crate::models::CitationsV2Query) -> StreamCitationsV2RequestBuilder {
        StreamCitationsV2RequestBuilder::new(self.client.clone(), body)
    }

    /// Stream Visibility V2
    pub fn stream_visibility_v2(&self, body: crate::models::VisibilityV2Query) -> StreamVisibilityV2RequestBuilder {
        StreamVisibilityV2RequestBuilder::new(self.client.clone(), body)
    }

    /// Stream Sentiment V2
    pub fn stream_sentiment_v2(&self, body: crate::models::SentimentV2Query) -> StreamSentimentV2RequestBuilder {
        StreamSentimentV2RequestBuilder::new(self.client.clone(), body)
    }

    /// Stream Query Fanouts V2
    pub fn stream_query_fanouts(&self, body: crate::models::QueryFanoutsV2Query) -> StreamQueryFanoutsRequestBuilder {
        StreamQueryFanoutsRequestBuilder::new(self.client.clone(), body)
    }

    /// Get Referrals Report V2
    pub fn get_referrals_report_v2(&self, body: crate::models::ReferralsQueryV2) -> GetReferralsReportV2RequestBuilder {
        GetReferralsReportV2RequestBuilder::new(self.client.clone(), body)
    }

    /// Get Bots Report V2
    pub fn get_bots_report_v2(&self, body: crate::models::BotsReportQueryV2) -> GetBotsReportV2RequestBuilder {
        GetBotsReportV2RequestBuilder::new(self.client.clone(), body)
    }

    /// Query Visibility V2
    pub fn query_visibility(&self, body: crate::models::VisibilityV2Query) -> QueryVisibilityRequestBuilder {
        QueryVisibilityRequestBuilder::new(self.client.clone(), body)
    }

    /// Query Citations V2
    pub fn query_citations(&self, body: crate::models::CitationsV2Query) -> QueryCitationsRequestBuilder {
        QueryCitationsRequestBuilder::new(self.client.clone(), body)
    }

    /// Query Sentiment V2
    pub fn query_sentiment(&self, body: crate::models::SentimentV2Query) -> QuerySentimentRequestBuilder {
        QuerySentimentRequestBuilder::new(self.client.clone(), body)
    }

    /// Query Fanouts V2
    pub fn query_query_fanouts(&self, body: crate::models::QueryFanoutsV2Query) -> QueryQueryFanoutsRequestBuilder {
        QueryQueryFanoutsRequestBuilder::new(self.client.clone(), body)
    }

    pub fn web_search_results(&self) -> crate::resources::web_search_results::WebSearchResultsResource {
        crate::resources::web_search_results::WebSearchResultsResource::new(self.client.clone())
    }

    pub fn shopping(&self) -> crate::resources::shopping::ShoppingResource {
        crate::resources::shopping::ShoppingResource::new(self.client.clone())
    }

    pub fn accuracy(&self) -> crate::resources::accuracy::AccuracyResource {
        crate::resources::accuracy::AccuracyResource::new(self.client.clone())
    }

    pub fn factcheck(&self) -> crate::resources::factcheck::FactcheckResource {
        crate::resources::factcheck::FactcheckResource::new(self.client.clone())
    }

    pub fn social(&self) -> crate::resources::social::SocialResource {
        crate::resources::social::SocialResource::new(self.client.clone())
    }
}

/// Get citations for a given category.
///
/// The ``mentioned`` filter supports ``is true`` and ``is false``. It uses the
/// latest page analysis available at or before ``end_date``; pages without an
/// analysis by then are excluded from both values. ``citation_share`` keeps all
/// otherwise eligible citations in its denominator when this filter is used.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CitationsRequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::CitationsQuery,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl CitationsRequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::CitationsQuery) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::CitationsResponse, crate::error::Error> {
        let path = "/v1/reports/citations".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::CitationsResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Query visibility report.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct VisibilityRequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::VisibilityQuery,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl VisibilityRequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::VisibilityQuery) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ReportResponse, crate::error::Error> {
        let path = "/v1/reports/visibility".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ReportResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Get citations for a given category.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct SentimentRequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::SentimentQuery,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl SentimentRequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::SentimentQuery) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ReportResponse, crate::error::Error> {
        let path = "/v1/reports/sentiment".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ReportResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Query Sentiment V2
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct SentimentV2RequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::SentimentV2ReportQuery,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl SentimentV2RequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::SentimentV2ReportQuery) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::SentimentV2ReportResponse, crate::error::Error> {
        let path = "/v1/reports/sentiment-v2".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::SentimentV2ReportResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Get referral traffic report from the daily aggregated materialized view.
///
/// This endpoint queries pre-aggregated daily referral data, making it efficient
/// for large date ranges and high-traffic sites.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct GetReferralsReportRequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::ReferralsQuery,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl GetReferralsReportRequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::ReferralsQuery) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ReportResponse, crate::error::Error> {
        let path = "/v1/reports/referrals".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ReportResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Get bot traffic report from the daily aggregated materialized view.
///
/// This endpoint queries pre-aggregated daily bot data, making it efficient
/// for large date ranges and high-traffic sites.
///
/// Metrics:
/// - count: unique bot visits
/// - citations: unique citation events
/// - indexing: unique indexing events
/// - training: unique training events
/// - last_visit: most recent visit timestamp
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct GetBotsReportRequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::BotsReportQuery,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl GetBotsReportRequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::BotsReportQuery) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ReportResponse, crate::error::Error> {
        let path = "/v1/reports/bots".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ReportResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Query Fanouts
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct QueryFanoutsRequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::QueryFanoutsQuery,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl QueryFanoutsRequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::QueryFanoutsQuery) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ReportResponse, crate::error::Error> {
        let path = "/v1/reports/query-fanouts".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ReportResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Stream citations with the same filter semantics as the non-streaming route.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct StreamCitationsRequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::StreamCitationsQuery,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
    event_timeout: Option<std::time::Duration>,
}

impl StreamCitationsRequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::StreamCitationsQuery) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
            event_timeout: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Fails the event stream if the server goes this long without
    /// sending more data.
    ///
    /// The client's request deadline only covers time-to-response-headers,
    /// which a streaming response passes immediately — without this bound a
    /// server that opens the stream and then goes silent hangs the consumer
    /// forever. The timer restarts on every chunk received, so a slow but
    /// live stream never trips it. Off unless set.
    pub fn event_timeout(mut self, event_timeout: std::time::Duration) -> Self {
        self.event_timeout = Some(event_timeout);
        self
    }

    /// Sends the request and returns a stream of decoded events.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    ///
    /// The returned stream yields a `Result` per event, so a body that stops
    /// mid-frame or an event that does not match the generated model surfaces on the
    /// item rather than here.
    pub async fn send(
        self,
    ) -> Result<crate::streaming::EventStream<crate::models::ReportsStreamCitationsResponse>, crate::error::Error> {
        let path = "/v1/reports/citations/stream".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = vec![("Accept".to_string(), "text/event-stream".to_string())];
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        let idle = self
            .event_timeout
            .map(|event_timeout| self.client.idle_timeout(event_timeout));
        let response = self
            .client
            .send_raw(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await?;
        crate::streaming::event_stream::<crate::models::ReportsStreamCitationsResponse>(
            response,
            crate::streaming::StreamFormat::Sse,
            self.client.max_response_size(),
            idle,
        )
        .await
    }

    /// Sends the request and returns a stream of decoded events, each paired
    /// with its Server-Sent Events metadata (`id`, `event`, `retry`).
    ///
    /// Use this over [`send`](Self::send) when the API multiplexes event types
    /// or you resume a stream from the last id it delivered.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    ///
    /// The returned stream yields a `Result` per event, so a body that stops
    /// mid-frame or an event that does not match the generated model surfaces on the
    /// item rather than here.
    pub async fn send_with_metadata(
        self,
    ) -> Result<
        crate::streaming::EventStream<crate::streaming::StreamEvent<crate::models::ReportsStreamCitationsResponse>>,
        crate::error::Error,
    > {
        let path = "/v1/reports/citations/stream".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = vec![("Accept".to_string(), "text/event-stream".to_string())];
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        let idle = self
            .event_timeout
            .map(|event_timeout| self.client.idle_timeout(event_timeout));
        let response = self
            .client
            .send_raw(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await?;
        crate::streaming::event_stream_with_metadata::<crate::models::ReportsStreamCitationsResponse>(
            response,
            crate::streaming::StreamFormat::Sse,
            self.client.max_response_size(),
            idle,
        )
        .await
    }
}
/// Stream Visibility
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct StreamVisibilityRequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::StreamVisibilityQuery,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
    event_timeout: Option<std::time::Duration>,
}

impl StreamVisibilityRequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::StreamVisibilityQuery) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
            event_timeout: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Fails the event stream if the server goes this long without
    /// sending more data.
    ///
    /// The client's request deadline only covers time-to-response-headers,
    /// which a streaming response passes immediately — without this bound a
    /// server that opens the stream and then goes silent hangs the consumer
    /// forever. The timer restarts on every chunk received, so a slow but
    /// live stream never trips it. Off unless set.
    pub fn event_timeout(mut self, event_timeout: std::time::Duration) -> Self {
        self.event_timeout = Some(event_timeout);
        self
    }

    /// Sends the request and returns a stream of decoded events.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    ///
    /// The returned stream yields a `Result` per event, so a body that stops
    /// mid-frame or an event that does not match the generated model surfaces on the
    /// item rather than here.
    pub async fn send(
        self,
    ) -> Result<crate::streaming::EventStream<crate::models::ReportsStreamVisibilityResponse>, crate::error::Error>
    {
        let path = "/v1/reports/visibility/stream".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = vec![("Accept".to_string(), "text/event-stream".to_string())];
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        let idle = self
            .event_timeout
            .map(|event_timeout| self.client.idle_timeout(event_timeout));
        let response = self
            .client
            .send_raw(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await?;
        crate::streaming::event_stream::<crate::models::ReportsStreamVisibilityResponse>(
            response,
            crate::streaming::StreamFormat::Sse,
            self.client.max_response_size(),
            idle,
        )
        .await
    }

    /// Sends the request and returns a stream of decoded events, each paired
    /// with its Server-Sent Events metadata (`id`, `event`, `retry`).
    ///
    /// Use this over [`send`](Self::send) when the API multiplexes event types
    /// or you resume a stream from the last id it delivered.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    ///
    /// The returned stream yields a `Result` per event, so a body that stops
    /// mid-frame or an event that does not match the generated model surfaces on the
    /// item rather than here.
    pub async fn send_with_metadata(
        self,
    ) -> Result<
        crate::streaming::EventStream<crate::streaming::StreamEvent<crate::models::ReportsStreamVisibilityResponse>>,
        crate::error::Error,
    > {
        let path = "/v1/reports/visibility/stream".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = vec![("Accept".to_string(), "text/event-stream".to_string())];
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        let idle = self
            .event_timeout
            .map(|event_timeout| self.client.idle_timeout(event_timeout));
        let response = self
            .client
            .send_raw(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await?;
        crate::streaming::event_stream_with_metadata::<crate::models::ReportsStreamVisibilityResponse>(
            response,
            crate::streaming::StreamFormat::Sse,
            self.client.max_response_size(),
            idle,
        )
        .await
    }
}
/// Stream Sentiment
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct StreamSentimentRequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::StreamSentimentQuery,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
    event_timeout: Option<std::time::Duration>,
}

impl StreamSentimentRequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::StreamSentimentQuery) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
            event_timeout: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Fails the event stream if the server goes this long without
    /// sending more data.
    ///
    /// The client's request deadline only covers time-to-response-headers,
    /// which a streaming response passes immediately — without this bound a
    /// server that opens the stream and then goes silent hangs the consumer
    /// forever. The timer restarts on every chunk received, so a slow but
    /// live stream never trips it. Off unless set.
    pub fn event_timeout(mut self, event_timeout: std::time::Duration) -> Self {
        self.event_timeout = Some(event_timeout);
        self
    }

    /// Sends the request and returns a stream of decoded events.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    ///
    /// The returned stream yields a `Result` per event, so a body that stops
    /// mid-frame or an event that does not match the generated model surfaces on the
    /// item rather than here.
    pub async fn send(
        self,
    ) -> Result<crate::streaming::EventStream<crate::models::ReportsStreamSentimentResponse>, crate::error::Error> {
        let path = "/v1/reports/sentiment/stream".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = vec![("Accept".to_string(), "text/event-stream".to_string())];
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        let idle = self
            .event_timeout
            .map(|event_timeout| self.client.idle_timeout(event_timeout));
        let response = self
            .client
            .send_raw(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await?;
        crate::streaming::event_stream::<crate::models::ReportsStreamSentimentResponse>(
            response,
            crate::streaming::StreamFormat::Sse,
            self.client.max_response_size(),
            idle,
        )
        .await
    }

    /// Sends the request and returns a stream of decoded events, each paired
    /// with its Server-Sent Events metadata (`id`, `event`, `retry`).
    ///
    /// Use this over [`send`](Self::send) when the API multiplexes event types
    /// or you resume a stream from the last id it delivered.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    ///
    /// The returned stream yields a `Result` per event, so a body that stops
    /// mid-frame or an event that does not match the generated model surfaces on the
    /// item rather than here.
    pub async fn send_with_metadata(
        self,
    ) -> Result<
        crate::streaming::EventStream<crate::streaming::StreamEvent<crate::models::ReportsStreamSentimentResponse>>,
        crate::error::Error,
    > {
        let path = "/v1/reports/sentiment/stream".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = vec![("Accept".to_string(), "text/event-stream".to_string())];
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        let idle = self
            .event_timeout
            .map(|event_timeout| self.client.idle_timeout(event_timeout));
        let response = self
            .client
            .send_raw(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await?;
        crate::streaming::event_stream_with_metadata::<crate::models::ReportsStreamSentimentResponse>(
            response,
            crate::streaming::StreamFormat::Sse,
            self.client.max_response_size(),
            idle,
        )
        .await
    }
}
/// Stream Citations V2
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct StreamCitationsV2RequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::CitationsV2Query,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
    event_timeout: Option<std::time::Duration>,
}

impl StreamCitationsV2RequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::CitationsV2Query) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
            event_timeout: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Fails the event stream if the server goes this long without
    /// sending more data.
    ///
    /// The client's request deadline only covers time-to-response-headers,
    /// which a streaming response passes immediately — without this bound a
    /// server that opens the stream and then goes silent hangs the consumer
    /// forever. The timer restarts on every chunk received, so a slow but
    /// live stream never trips it. Off unless set.
    pub fn event_timeout(mut self, event_timeout: std::time::Duration) -> Self {
        self.event_timeout = Some(event_timeout);
        self
    }

    /// Sends the request and returns a stream of decoded events.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    ///
    /// The returned stream yields a `Result` per event, so a body that stops
    /// mid-frame or an event that does not match the generated model surfaces on the
    /// item rather than here.
    pub async fn send(
        self,
    ) -> Result<crate::streaming::EventStream<crate::models::ReportsStreamCitationsV2Response>, crate::error::Error>
    {
        let path = "/v2/reports/citations/stream".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = vec![("Accept".to_string(), "text/event-stream".to_string())];
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        let idle = self
            .event_timeout
            .map(|event_timeout| self.client.idle_timeout(event_timeout));
        let response = self
            .client
            .send_raw(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await?;
        crate::streaming::event_stream::<crate::models::ReportsStreamCitationsV2Response>(
            response,
            crate::streaming::StreamFormat::Sse,
            self.client.max_response_size(),
            idle,
        )
        .await
    }

    /// Sends the request and returns a stream of decoded events, each paired
    /// with its Server-Sent Events metadata (`id`, `event`, `retry`).
    ///
    /// Use this over [`send`](Self::send) when the API multiplexes event types
    /// or you resume a stream from the last id it delivered.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    ///
    /// The returned stream yields a `Result` per event, so a body that stops
    /// mid-frame or an event that does not match the generated model surfaces on the
    /// item rather than here.
    pub async fn send_with_metadata(
        self,
    ) -> Result<
        crate::streaming::EventStream<crate::streaming::StreamEvent<crate::models::ReportsStreamCitationsV2Response>>,
        crate::error::Error,
    > {
        let path = "/v2/reports/citations/stream".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = vec![("Accept".to_string(), "text/event-stream".to_string())];
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        let idle = self
            .event_timeout
            .map(|event_timeout| self.client.idle_timeout(event_timeout));
        let response = self
            .client
            .send_raw(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await?;
        crate::streaming::event_stream_with_metadata::<crate::models::ReportsStreamCitationsV2Response>(
            response,
            crate::streaming::StreamFormat::Sse,
            self.client.max_response_size(),
            idle,
        )
        .await
    }
}
/// Stream Visibility V2
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct StreamVisibilityV2RequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::VisibilityV2Query,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
    event_timeout: Option<std::time::Duration>,
}

impl StreamVisibilityV2RequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::VisibilityV2Query) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
            event_timeout: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Fails the event stream if the server goes this long without
    /// sending more data.
    ///
    /// The client's request deadline only covers time-to-response-headers,
    /// which a streaming response passes immediately — without this bound a
    /// server that opens the stream and then goes silent hangs the consumer
    /// forever. The timer restarts on every chunk received, so a slow but
    /// live stream never trips it. Off unless set.
    pub fn event_timeout(mut self, event_timeout: std::time::Duration) -> Self {
        self.event_timeout = Some(event_timeout);
        self
    }

    /// Sends the request and returns a stream of decoded events.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    ///
    /// The returned stream yields a `Result` per event, so a body that stops
    /// mid-frame or an event that does not match the generated model surfaces on the
    /// item rather than here.
    pub async fn send(
        self,
    ) -> Result<crate::streaming::EventStream<crate::models::ReportsStreamVisibilityV2Response>, crate::error::Error>
    {
        let path = "/v2/reports/visibility/stream".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = vec![("Accept".to_string(), "text/event-stream".to_string())];
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        let idle = self
            .event_timeout
            .map(|event_timeout| self.client.idle_timeout(event_timeout));
        let response = self
            .client
            .send_raw(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await?;
        crate::streaming::event_stream::<crate::models::ReportsStreamVisibilityV2Response>(
            response,
            crate::streaming::StreamFormat::Sse,
            self.client.max_response_size(),
            idle,
        )
        .await
    }

    /// Sends the request and returns a stream of decoded events, each paired
    /// with its Server-Sent Events metadata (`id`, `event`, `retry`).
    ///
    /// Use this over [`send`](Self::send) when the API multiplexes event types
    /// or you resume a stream from the last id it delivered.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    ///
    /// The returned stream yields a `Result` per event, so a body that stops
    /// mid-frame or an event that does not match the generated model surfaces on the
    /// item rather than here.
    pub async fn send_with_metadata(
        self,
    ) -> Result<
        crate::streaming::EventStream<crate::streaming::StreamEvent<crate::models::ReportsStreamVisibilityV2Response>>,
        crate::error::Error,
    > {
        let path = "/v2/reports/visibility/stream".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = vec![("Accept".to_string(), "text/event-stream".to_string())];
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        let idle = self
            .event_timeout
            .map(|event_timeout| self.client.idle_timeout(event_timeout));
        let response = self
            .client
            .send_raw(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await?;
        crate::streaming::event_stream_with_metadata::<crate::models::ReportsStreamVisibilityV2Response>(
            response,
            crate::streaming::StreamFormat::Sse,
            self.client.max_response_size(),
            idle,
        )
        .await
    }
}
/// Stream Sentiment V2
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct StreamSentimentV2RequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::SentimentV2Query,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
    event_timeout: Option<std::time::Duration>,
}

impl StreamSentimentV2RequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::SentimentV2Query) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
            event_timeout: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Fails the event stream if the server goes this long without
    /// sending more data.
    ///
    /// The client's request deadline only covers time-to-response-headers,
    /// which a streaming response passes immediately — without this bound a
    /// server that opens the stream and then goes silent hangs the consumer
    /// forever. The timer restarts on every chunk received, so a slow but
    /// live stream never trips it. Off unless set.
    pub fn event_timeout(mut self, event_timeout: std::time::Duration) -> Self {
        self.event_timeout = Some(event_timeout);
        self
    }

    /// Sends the request and returns a stream of decoded events.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    ///
    /// The returned stream yields a `Result` per event, so a body that stops
    /// mid-frame or an event that does not match the generated model surfaces on the
    /// item rather than here.
    pub async fn send(
        self,
    ) -> Result<crate::streaming::EventStream<crate::models::ReportsStreamSentimentV2Response>, crate::error::Error>
    {
        let path = "/v2/reports/sentiment/stream".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = vec![("Accept".to_string(), "text/event-stream".to_string())];
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        let idle = self
            .event_timeout
            .map(|event_timeout| self.client.idle_timeout(event_timeout));
        let response = self
            .client
            .send_raw(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await?;
        crate::streaming::event_stream::<crate::models::ReportsStreamSentimentV2Response>(
            response,
            crate::streaming::StreamFormat::Sse,
            self.client.max_response_size(),
            idle,
        )
        .await
    }

    /// Sends the request and returns a stream of decoded events, each paired
    /// with its Server-Sent Events metadata (`id`, `event`, `retry`).
    ///
    /// Use this over [`send`](Self::send) when the API multiplexes event types
    /// or you resume a stream from the last id it delivered.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    ///
    /// The returned stream yields a `Result` per event, so a body that stops
    /// mid-frame or an event that does not match the generated model surfaces on the
    /// item rather than here.
    pub async fn send_with_metadata(
        self,
    ) -> Result<
        crate::streaming::EventStream<crate::streaming::StreamEvent<crate::models::ReportsStreamSentimentV2Response>>,
        crate::error::Error,
    > {
        let path = "/v2/reports/sentiment/stream".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = vec![("Accept".to_string(), "text/event-stream".to_string())];
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        let idle = self
            .event_timeout
            .map(|event_timeout| self.client.idle_timeout(event_timeout));
        let response = self
            .client
            .send_raw(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await?;
        crate::streaming::event_stream_with_metadata::<crate::models::ReportsStreamSentimentV2Response>(
            response,
            crate::streaming::StreamFormat::Sse,
            self.client.max_response_size(),
            idle,
        )
        .await
    }
}
/// Stream Query Fanouts V2
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct StreamQueryFanoutsRequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::QueryFanoutsV2Query,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
    event_timeout: Option<std::time::Duration>,
}

impl StreamQueryFanoutsRequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::QueryFanoutsV2Query) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
            event_timeout: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Fails the event stream if the server goes this long without
    /// sending more data.
    ///
    /// The client's request deadline only covers time-to-response-headers,
    /// which a streaming response passes immediately — without this bound a
    /// server that opens the stream and then goes silent hangs the consumer
    /// forever. The timer restarts on every chunk received, so a slow but
    /// live stream never trips it. Off unless set.
    pub fn event_timeout(mut self, event_timeout: std::time::Duration) -> Self {
        self.event_timeout = Some(event_timeout);
        self
    }

    /// Sends the request and returns a stream of decoded events.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    ///
    /// The returned stream yields a `Result` per event, so a body that stops
    /// mid-frame or an event that does not match the generated model surfaces on the
    /// item rather than here.
    pub async fn send(
        self,
    ) -> Result<crate::streaming::EventStream<crate::models::ReportsStreamQueryFanoutsResponse>, crate::error::Error>
    {
        let path = "/v2/reports/query-fanouts/stream".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = vec![("Accept".to_string(), "text/event-stream".to_string())];
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        let idle = self
            .event_timeout
            .map(|event_timeout| self.client.idle_timeout(event_timeout));
        let response = self
            .client
            .send_raw(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await?;
        crate::streaming::event_stream::<crate::models::ReportsStreamQueryFanoutsResponse>(
            response,
            crate::streaming::StreamFormat::Sse,
            self.client.max_response_size(),
            idle,
        )
        .await
    }

    /// Sends the request and returns a stream of decoded events, each paired
    /// with its Server-Sent Events metadata (`id`, `event`, `retry`).
    ///
    /// Use this over [`send`](Self::send) when the API multiplexes event types
    /// or you resume a stream from the last id it delivered.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    ///
    /// The returned stream yields a `Result` per event, so a body that stops
    /// mid-frame or an event that does not match the generated model surfaces on the
    /// item rather than here.
    pub async fn send_with_metadata(
        self,
    ) -> Result<
        crate::streaming::EventStream<crate::streaming::StreamEvent<crate::models::ReportsStreamQueryFanoutsResponse>>,
        crate::error::Error,
    > {
        let path = "/v2/reports/query-fanouts/stream".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = vec![("Accept".to_string(), "text/event-stream".to_string())];
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        let idle = self
            .event_timeout
            .map(|event_timeout| self.client.idle_timeout(event_timeout));
        let response = self
            .client
            .send_raw(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await?;
        crate::streaming::event_stream_with_metadata::<crate::models::ReportsStreamQueryFanoutsResponse>(
            response,
            crate::streaming::StreamFormat::Sse,
            self.client.max_response_size(),
            idle,
        )
        .await
    }
}
/// Get referral traffic report from the hourly aggregated materialized view (UTC-based).
///
/// Supports date_interval="hour", calendar intervals through "year", "quarter", and "relative_week".
/// When `view_id` is provided, the query is scoped to that domain segment's hosts and paths.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct GetReferralsReportV2RequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::ReferralsQueryV2,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl GetReferralsReportV2RequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::ReferralsQueryV2) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ReportResponse, crate::error::Error> {
        let path = "/v2/reports/referrals".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ReportResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Get bot traffic report from the hourly aggregated materialized view (UTC-based).
///
/// Supports date_interval="hour", calendar intervals through "year", "quarter", and "relative_week".
/// When `view_id` is provided, the query is scoped to that domain segment's hosts and paths.
///
/// Metrics:
/// - count: unique bot visits
/// - citations: unique citation events (ai_assistant bot type)
/// - indexing: unique indexing events (index bot type)
/// - training: unique training events (ai_training bot type)
/// - last_visit: most recent visit timestamp
///
/// Dimensions:
/// - date, path, bot_name, bot_provider, bot_type
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct GetBotsReportV2RequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::BotsReportQueryV2,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl GetBotsReportV2RequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::BotsReportQueryV2) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ReportResponse, crate::error::Error> {
        let path = "/v2/reports/bots".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ReportResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Query Visibility V2
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct QueryVisibilityRequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::VisibilityV2Query,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl QueryVisibilityRequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::VisibilityV2Query) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::VisibilityV2Response, crate::error::Error> {
        let path = "/v2/reports/visibility".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::VisibilityV2Response, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Query Citations V2
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct QueryCitationsRequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::CitationsV2Query,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl QueryCitationsRequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::CitationsV2Query) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::CitationsV2Response, crate::error::Error> {
        let path = "/v2/reports/citations".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::CitationsV2Response, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Query Sentiment V2
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct QuerySentimentRequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::SentimentV2Query,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl QuerySentimentRequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::SentimentV2Query) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::SentimentV2Response, crate::error::Error> {
        let path = "/v2/reports/sentiment".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::SentimentV2Response, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Query Fanouts V2
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct QueryQueryFanoutsRequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::QueryFanoutsV2Query,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl QueryQueryFanoutsRequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::QueryFanoutsV2Query) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::QueryFanoutsV2Response, crate::error::Error> {
        let path = "/v2/reports/query-fanouts".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::QueryFanoutsV2Response, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
