// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `volume` resource.

#[derive(Clone)]
pub struct VolumeResource {
    client: crate::client::ProfoundClient,
}

impl VolumeResource {
    pub(crate) fn new(client: crate::client::ProfoundClient) -> Self {
        Self { client }
    }

    /// Get Keyword Volume
    pub fn on_the_fly(&self, body: crate::models::OtfVolumeRequest) -> OnTheFlyRequestBuilder {
        OnTheFlyRequestBuilder::new(self.client.clone(), body)
    }
}

/// Weekly and monthly volume projections for one keyword.
///
/// Each organization can look up 1,000 distinct keywords per UTC day; over
/// the cap returns 429 with Retry-After. Slices with two or fewer users are
/// omitted for privacy.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct OnTheFlyRequestBuilder {
    client: crate::client::ProfoundClient,
    body: crate::models::OtfVolumeRequest,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl OnTheFlyRequestBuilder {
    fn new(client: crate::client::ProfoundClient, body: crate::models::OtfVolumeRequest) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::OtfVolumeResponse, crate::error::Error> {
        let path = "/v2/prompt-volumes/volume/on-the-fly".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::OtfVolumeResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
