// Generated by scripts/generate_filter_table.py from the x-profound-filter-grammar extension of the Profound OpenAPI spec. Do not edit by hand.

pub const MAX_DEPTH: usize = 3;

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Layer {
    Prompt,
    Entity,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Op {
    Is,
    NotIs,
    In,
    NotIn,
    Contains,
    NotContains,
    Matches,
    ContainsCaseInsensitive,
    NotContainsCaseInsensitive,
    Exists,
}

impl Op {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Is => "is",
            Self::NotIs => "not_is",
            Self::In => "in",
            Self::NotIn => "not_in",
            Self::Contains => "contains",
            Self::NotContains => "not_contains",
            Self::Matches => "matches",
            Self::ContainsCaseInsensitive => "contains_case_insensitive",
            Self::NotContainsCaseInsensitive => "not_contains_case_insensitive",
            Self::Exists => "exists",
        }
    }
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Field {
    AnalysisType,
    CitationCategory,
    CitationTag,
    Claim,
    Domain,
    Model,
    Page,
    Persona,
    Prompt,
    Region,
    Tag,
    Theme,
    Topic,
}

pub const ALL_FIELDS: &[Field] = &[
    Field::AnalysisType,
    Field::CitationCategory,
    Field::CitationTag,
    Field::Claim,
    Field::Domain,
    Field::Model,
    Field::Page,
    Field::Persona,
    Field::Prompt,
    Field::Region,
    Field::Tag,
    Field::Theme,
    Field::Topic,
];

impl Field {
    pub fn name(self) -> &'static str {
        match self {
            Self::AnalysisType => "analysis_type",
            Self::CitationCategory => "citation_category",
            Self::CitationTag => "citation_tag",
            Self::Claim => "claim",
            Self::Domain => "domain",
            Self::Model => "model",
            Self::Page => "page",
            Self::Persona => "persona",
            Self::Prompt => "prompt",
            Self::Region => "region",
            Self::Tag => "tag",
            Self::Theme => "theme",
            Self::Topic => "topic",
        }
    }

    pub fn layer(self) -> Layer {
        match self {
            Self::AnalysisType => Layer::Entity,
            Self::CitationCategory => Layer::Entity,
            Self::CitationTag => Layer::Entity,
            Self::Claim => Layer::Entity,
            Self::Domain => Layer::Entity,
            Self::Model => Layer::Prompt,
            Self::Page => Layer::Entity,
            Self::Persona => Layer::Prompt,
            Self::Prompt => Layer::Prompt,
            Self::Region => Layer::Prompt,
            Self::Tag => Layer::Prompt,
            Self::Theme => Layer::Entity,
            Self::Topic => Layer::Prompt,
        }
    }

    pub fn ops(self) -> &'static [Op] {
        match self {
            Self::AnalysisType => &[Op::Is, Op::NotIs, Op::In, Op::NotIn],
            Self::CitationCategory => &[Op::Is, Op::In],
            Self::CitationTag => &[Op::Is, Op::In],
            Self::Claim => &[Op::Is, Op::In],
            Self::Domain => &[
                Op::Is,
                Op::NotIs,
                Op::In,
                Op::NotIn,
                Op::Contains,
                Op::NotContains,
                Op::Matches,
                Op::ContainsCaseInsensitive,
                Op::NotContainsCaseInsensitive,
            ],
            Self::Model => &[
                Op::Is,
                Op::NotIs,
                Op::In,
                Op::NotIn,
                Op::Contains,
                Op::NotContains,
                Op::Matches,
                Op::ContainsCaseInsensitive,
                Op::NotContainsCaseInsensitive,
            ],
            Self::Page => &[
                Op::Is,
                Op::NotIs,
                Op::In,
                Op::NotIn,
                Op::Contains,
                Op::NotContains,
                Op::Matches,
                Op::ContainsCaseInsensitive,
                Op::NotContainsCaseInsensitive,
            ],
            Self::Persona => &[
                Op::Is,
                Op::NotIs,
                Op::In,
                Op::NotIn,
                Op::Contains,
                Op::NotContains,
                Op::Matches,
                Op::ContainsCaseInsensitive,
                Op::NotContainsCaseInsensitive,
                Op::Exists,
            ],
            Self::Prompt => &[
                Op::Is,
                Op::NotIs,
                Op::In,
                Op::NotIn,
                Op::Contains,
                Op::NotContains,
                Op::Matches,
                Op::ContainsCaseInsensitive,
                Op::NotContainsCaseInsensitive,
            ],
            Self::Region => &[
                Op::Is,
                Op::NotIs,
                Op::In,
                Op::NotIn,
                Op::Contains,
                Op::NotContains,
                Op::Matches,
                Op::ContainsCaseInsensitive,
                Op::NotContainsCaseInsensitive,
            ],
            Self::Tag => &[
                Op::Is,
                Op::NotIs,
                Op::In,
                Op::NotIn,
                Op::Contains,
                Op::NotContains,
                Op::Matches,
                Op::ContainsCaseInsensitive,
                Op::NotContainsCaseInsensitive,
                Op::Exists,
            ],
            Self::Theme => &[Op::Is, Op::In],
            Self::Topic => &[
                Op::Is,
                Op::NotIs,
                Op::In,
                Op::NotIn,
                Op::Contains,
                Op::NotContains,
                Op::Matches,
                Op::ContainsCaseInsensitive,
                Op::NotContainsCaseInsensitive,
            ],
        }
    }
}
