// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Streaming example: a streaming operation returns a stream of decoded
//! events from `send().await`, framed as Server-Sent Events or JSON
//! Lines depending on what the endpoint serves.
//!
//! ```sh
//! cargo run --example streaming
//! ```
#![allow(unused)]

use futures::StreamExt;
use profound::*;

/// Environment variable naming the server the guarded `main` dials.
const BASE_URL_ENV: &str = "PROFOUND_BASE_URL";

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let Ok(base_url) = std::env::var(BASE_URL_ENV) else {
        println!("Set {BASE_URL_ENV} to run this example against a server.");
        return Ok(());
    };
    let client = ProfoundClient::builder().base_url(base_url).build()?;

    let mut events = client
        .prompts()
        .stream_answers_v2(AnswersV2Query {
            category_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7".to_string(),
            start_date: "".to_string(),
            end_date: "".to_string(),
            include: None,
            filter: None,
            limit: None,
            max_results: None,
            cursor: None,
        })
        .send()
        .await?;
    while let Some(event) = events.next().await {
        let event = event?;
        println!("{event:?}");
    }

    // `send_with_metadata()` yields the same events paired with their
    // Server-Sent Events `id`/`event`/`retry` fields.

    Ok(())
}
