// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `accuracy`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AccuracyBreakdownQuery {
    pub start_date: String,
    pub end_date: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_start_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_end_date: Option<String>,
    pub category_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exclude_topic_ids: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_filter_type: Option<AccuracyBreakdownQueryTagFilterType>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_tag: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub platform_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub persona_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_persona: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub citation_categories: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub breakdown_by: Option<AccuracyBreakdownQueryBreakdownBy>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_by: Option<Vec<AccuracyBreakdownQueryGroupBy>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub date_bucket: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub search_query: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<AccuracyBreakdownQuerySortBy>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<AccuracyBreakdownQuerySortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pagination: Option<AccuracyPagination>,
}

impl AccuracyBreakdownQuery {
    /// Creates a new `AccuracyBreakdownQuery` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `AccuracyBreakdownQuery { comparison_start_date: Some(…), ..AccuracyBreakdownQuery::new(…) }`.
    pub fn new(start_date: impl Into<String>, end_date: impl Into<String>, category_id: impl Into<String>) -> Self {
        Self {
            start_date: start_date.into(),
            end_date: end_date.into(),
            comparison_start_date: None,
            comparison_end_date: None,
            category_id: category_id.into(),
            topic_ids: None,
            exclude_topic_ids: None,
            tag_ids: None,
            tag_filter_type: None,
            include_no_tag: None,
            region_ids: None,
            platform_ids: None,
            persona_ids: None,
            include_no_persona: None,
            prompt_ids: None,
            citation_categories: None,
            breakdown_by: None,
            group_by: None,
            date_bucket: None,
            limit: None,
            offset: None,
            search_query: None,
            sort_by: None,
            sort_order: None,
            pagination: None,
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AccuracyBreakdownResponse {
    pub data: Vec<AccuracyBreakdownRow>,
    #[serde(rename = "totalCount")]
    pub total_count: i64,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AccuracyBreakdownRow {
    pub id: String,
    pub name: String,
    #[serde(rename = "groupIds", default, skip_serializing_if = "Option::is_none")]
    pub group_ids: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "groupNames", default, skip_serializing_if = "Option::is_none")]
    pub group_names: Option<std::collections::HashMap<String, String>>,
    pub share: f64,
    #[serde(rename = "shareChange", default, skip_serializing_if = "Option::is_none")]
    pub share_change: Option<f64>,
    #[serde(rename = "responseAccuracy")]
    pub response_accuracy: f64,
    #[serde(rename = "accuracyChange", default, skip_serializing_if = "Option::is_none")]
    pub accuracy_change: Option<f64>,
    #[serde(rename = "accurateCount", default, skip_serializing_if = "Option::is_none")]
    pub accurate_count: Option<i64>,
    #[serde(rename = "inaccurateCount")]
    pub inaccurate_count: i64,
    #[serde(rename = "inaccurateCountChange", default, skip_serializing_if = "Option::is_none")]
    pub inaccurate_count_change: Option<i64>,
    #[serde(rename = "promptCount", default, skip_serializing_if = "Option::is_none")]
    pub prompt_count: Option<i64>,
    #[serde(rename = "citationCategory", default, skip_serializing_if = "Option::is_none")]
    pub citation_category: Option<String>,
    #[serde(rename = "hasScore", default, skip_serializing_if = "Option::is_none")]
    pub has_score: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AccuracyCitationAnalysisQuery {
    pub category_id: String,
    pub clean_href: String,
    pub start_date: String,
    pub end_date: String,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AccuracyCitationAnalysisResponse {
    pub href: String,
    pub domain: String,
    #[serde(rename = "pageTitle")]
    pub page_title: String,
    #[serde(rename = "markdownContent")]
    pub markdown_content: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub claims: Option<Vec<AccuracyCitationClaim>>,
}

/// A single inaccurate claim mapped to a cluster, surfaced on a cited page.
///
/// ``attribute`` carries the cluster's canonical claim so the drawer can group
/// claims the same way it groups sentiment attributes.
///
/// ``reasoning`` and ``evidence`` mirror the cluster's FactCheck verdict: the
/// "why it's inaccurate" explanation plus the refuting knowledge-base snippets
/// surfaced in the Claim Analysis drawer. ``kb_path``/``kb_snippet`` are retained
/// as the cluster's single representative snippet for backward compatibility.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AccuracyCitationClaim {
    #[serde(rename = "claimId")]
    pub claim_id: String,
    pub claim: String,
    #[serde(rename = "attributeId")]
    pub attribute_id: String,
    pub attribute: String,
    #[serde(rename = "neutralThemeId")]
    pub neutral_theme_id: String,
    #[serde(rename = "neutralTheme")]
    pub neutral_theme: String,
    pub snippet: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub polarity: Option<AccuracyCitationClaimPolarity>,
    #[serde(rename = "kbPath", default, skip_serializing_if = "Option::is_none")]
    pub kb_path: Option<String>,
    #[serde(rename = "kbSnippet", default, skip_serializing_if = "Option::is_none")]
    pub kb_snippet: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub evidence: Option<Vec<AccuracyCitationEvidence>>,
}

/// A single knowledge-base ground-truth snippet that refutes a claim's cluster.
///
/// ``kb_name`` is the official knowledge base name; ``kb_path`` is the document
/// path within that knowledge base. ``kb_name`` is populated by the external API
/// layer (which can reach the knowledge-base service) and defaults to ``""``
/// elsewhere.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AccuracyCitationEvidence {
    #[serde(rename = "kbName", default, skip_serializing_if = "Option::is_none")]
    pub kb_name: Option<String>,
    #[serde(rename = "kbPath", default, skip_serializing_if = "Option::is_none")]
    pub kb_path: Option<String>,
    #[serde(rename = "kbSnippet", default, skip_serializing_if = "Option::is_none")]
    pub kb_snippet: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AccuracyOverviewQuery {
    pub start_date: String,
    pub end_date: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_start_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_end_date: Option<String>,
    pub category_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exclude_topic_ids: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_filter_type: Option<AccuracyOverviewQueryTagFilterType>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_tag: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub platform_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub persona_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_persona: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub citation_categories: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub date_bucket: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_by: Option<AccuracyOverviewQueryGroupBy>,
}

impl AccuracyOverviewQuery {
    /// Creates a new `AccuracyOverviewQuery` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `AccuracyOverviewQuery { comparison_start_date: Some(…), ..AccuracyOverviewQuery::new(…) }`.
    pub fn new(start_date: impl Into<String>, end_date: impl Into<String>, category_id: impl Into<String>) -> Self {
        Self {
            start_date: start_date.into(),
            end_date: end_date.into(),
            comparison_start_date: None,
            comparison_end_date: None,
            category_id: category_id.into(),
            topic_ids: None,
            exclude_topic_ids: None,
            tag_ids: None,
            tag_filter_type: None,
            include_no_tag: None,
            region_ids: None,
            platform_ids: None,
            persona_ids: None,
            include_no_persona: None,
            prompt_ids: None,
            citation_categories: None,
            date_bucket: None,
            group_by: None,
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AccuracyOverviewResponse {
    #[serde(rename = "trendByPeriod")]
    pub trend_by_period: Vec<AccuracyTrendPoint>,
    #[serde(rename = "overallAccuracy")]
    pub overall_accuracy: f64,
    #[serde(rename = "accuracyChange", default, skip_serializing_if = "Option::is_none")]
    pub accuracy_change: Option<f64>,
    #[serde(rename = "scoreBreakdown")]
    pub score_breakdown: Vec<AccuracyScoreBreakdown>,
    #[serde(rename = "themeTrend", default, skip_serializing_if = "Option::is_none")]
    pub theme_trend: Option<Vec<AccuracyThemeTrendSeries>>,
    #[serde(rename = "availableSeries", default, skip_serializing_if = "Option::is_none")]
    pub available_series: Option<Vec<AccuracyTrendSeriesMeta>>,
}

/// Canonical grouped pagination plan for Accuracy Breakdown rows.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AccuracyPagination {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dimension: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metric: Option<AccuracyPaginationMetric>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<AccuracyPaginationMode>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub direction: Option<AccuracyPaginationDirection>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AccuracyScoreBreakdown {
    pub status: String,
    pub count: i64,
    pub share: f64,
    #[serde(rename = "countChange", default, skip_serializing_if = "Option::is_none")]
    pub count_change: Option<i64>,
    #[serde(rename = "shareChange", default, skip_serializing_if = "Option::is_none")]
    pub share_change: Option<f64>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AccuracyThemeTrendPoint {
    pub date: String,
    pub total: i64,
    pub accurate: i64,
    pub ratio: f64,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AccuracyThemeTrendSeries {
    pub id: String,
    pub label: String,
    pub data: Vec<AccuracyThemeTrendPoint>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AccuracyTopicIdsQuery {
    pub category_id: String,
    pub start_date: String,
    pub end_date: String,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AccuracyTrendPoint {
    pub date: String,
    pub total: i64,
    pub accurate: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verified: Option<i64>,
    pub ratio: f64,
    #[serde(rename = "prevPeriodData", default, skip_serializing_if = "Option::is_none")]
    pub prev_period_data: Option<Box<AccuracyTrendPoint>>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AccuracyTrendSeriesMeta {
    pub id: String,
    pub label: String,
    pub total: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ClaimBreakdownQuery {
    pub start_date: String,
    pub end_date: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_start_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_end_date: Option<String>,
    pub category_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exclude_topic_ids: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_filter_type: Option<ClaimBreakdownQueryTagFilterType>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_tag: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub platform_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub persona_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_persona: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub citation_categories: Option<Vec<String>>,
    pub cluster_id: String,
}

impl ClaimBreakdownQuery {
    /// Creates a new `ClaimBreakdownQuery` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `ClaimBreakdownQuery { comparison_start_date: Some(…), ..ClaimBreakdownQuery::new(…) }`.
    pub fn new(
        start_date: impl Into<String>,
        end_date: impl Into<String>,
        category_id: impl Into<String>,
        cluster_id: impl Into<String>,
    ) -> Self {
        Self {
            start_date: start_date.into(),
            end_date: end_date.into(),
            comparison_start_date: None,
            comparison_end_date: None,
            category_id: category_id.into(),
            topic_ids: None,
            exclude_topic_ids: None,
            tag_ids: None,
            tag_filter_type: None,
            include_no_tag: None,
            region_ids: None,
            platform_ids: None,
            persona_ids: None,
            include_no_persona: None,
            prompt_ids: None,
            citation_categories: None,
            cluster_id: cluster_id.into(),
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ClaimBreakdownResponse {
    pub platform: Vec<ClaimBreakdownRow>,
    pub prompt: Vec<ClaimPromptBreakdownRow>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ClaimBreakdownRow {
    pub id: String,
    pub label: String,
    #[serde(rename = "responseCount")]
    pub response_count: i64,
    #[serde(rename = "totalResponseCount")]
    pub total_response_count: i64,
    #[serde(rename = "responseShare")]
    pub response_share: f64,
    #[serde(rename = "responseShareDelta", default, skip_serializing_if = "Option::is_none")]
    pub response_share_delta: Option<f64>,
    #[serde(rename = "prevResponseCount")]
    pub prev_response_count: i64,
    #[serde(rename = "prevTotalResponseCount")]
    pub prev_total_response_count: i64,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ClaimCitationRow {
    pub href: String,
    pub hostname: String,
    pub path: String,
    #[serde(rename = "citationCategory")]
    pub citation_category: String,
    #[serde(rename = "domainCategory")]
    pub domain_category: String,
    pub snippet: String,
    #[serde(rename = "citationCount")]
    pub citation_count: f64,
    #[serde(rename = "citationShare")]
    pub citation_share: f64,
    #[serde(rename = "citationShareDelta", default, skip_serializing_if = "Option::is_none")]
    pub citation_share_delta: Option<f64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ClaimCitationsQuery {
    pub start_date: String,
    pub end_date: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_start_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_end_date: Option<String>,
    pub category_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exclude_topic_ids: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_filter_type: Option<ClaimCitationsQueryTagFilterType>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_tag: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub platform_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub persona_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_persona: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub citation_categories: Option<Vec<String>>,
    pub cluster_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub search_query: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<ClaimCitationsQuerySortOrder>,
}

impl ClaimCitationsQuery {
    /// Creates a new `ClaimCitationsQuery` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `ClaimCitationsQuery { comparison_start_date: Some(…), ..ClaimCitationsQuery::new(…) }`.
    pub fn new(
        start_date: impl Into<String>,
        end_date: impl Into<String>,
        category_id: impl Into<String>,
        cluster_id: impl Into<String>,
    ) -> Self {
        Self {
            start_date: start_date.into(),
            end_date: end_date.into(),
            comparison_start_date: None,
            comparison_end_date: None,
            category_id: category_id.into(),
            topic_ids: None,
            exclude_topic_ids: None,
            tag_ids: None,
            tag_filter_type: None,
            include_no_tag: None,
            region_ids: None,
            platform_ids: None,
            persona_ids: None,
            include_no_persona: None,
            prompt_ids: None,
            citation_categories: None,
            cluster_id: cluster_id.into(),
            limit: None,
            offset: None,
            search_query: None,
            sort_order: None,
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ClaimCitationsResponse {
    pub data: Vec<ClaimCitationRow>,
    #[serde(rename = "totalCount")]
    pub total_count: i64,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ClaimPromptBreakdownRow {
    pub id: String,
    pub label: String,
    #[serde(rename = "responseCount")]
    pub response_count: i64,
    #[serde(rename = "totalResponseCount")]
    pub total_response_count: i64,
    #[serde(rename = "responseShare")]
    pub response_share: f64,
    #[serde(rename = "responseShareDelta", default, skip_serializing_if = "Option::is_none")]
    pub response_share_delta: Option<f64>,
    #[serde(rename = "prevResponseCount")]
    pub prev_response_count: i64,
    #[serde(rename = "prevTotalResponseCount")]
    pub prev_total_response_count: i64,
    #[serde(rename = "promptId")]
    pub prompt_id: String,
    #[serde(rename = "promptText")]
    pub prompt_text: String,
    #[serde(rename = "topicId")]
    pub topic_id: String,
    #[serde(rename = "hasCurrent")]
    pub has_current: bool,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ClusterExampleRun {
    #[serde(rename = "runId")]
    pub run_id: String,
    pub claim: String,
    #[serde(rename = "responseSnippet")]
    pub response_snippet: String,
    #[serde(rename = "modelId")]
    pub model_id: String,
    #[serde(rename = "regionId")]
    pub region_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ClusterExampleRunsQuery {
    pub start_date: String,
    pub end_date: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_start_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_end_date: Option<String>,
    pub category_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exclude_topic_ids: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_filter_type: Option<ClusterExampleRunsQueryTagFilterType>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_tag: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub platform_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub persona_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_persona: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub citation_categories: Option<Vec<String>>,
    pub cluster_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
}

impl ClusterExampleRunsQuery {
    /// Creates a new `ClusterExampleRunsQuery` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `ClusterExampleRunsQuery { comparison_start_date: Some(…), ..ClusterExampleRunsQuery::new(…) }`.
    pub fn new(
        start_date: impl Into<String>,
        end_date: impl Into<String>,
        category_id: impl Into<String>,
        cluster_id: impl Into<String>,
    ) -> Self {
        Self {
            start_date: start_date.into(),
            end_date: end_date.into(),
            comparison_start_date: None,
            comparison_end_date: None,
            category_id: category_id.into(),
            topic_ids: None,
            exclude_topic_ids: None,
            tag_ids: None,
            tag_filter_type: None,
            include_no_tag: None,
            region_ids: None,
            platform_ids: None,
            persona_ids: None,
            include_no_persona: None,
            prompt_ids: None,
            citation_categories: None,
            cluster_id: cluster_id.into(),
            limit: None,
            offset: None,
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ClusterExampleRunsResponse {
    pub data: Vec<ClusterExampleRun>,
    #[serde(rename = "totalCount")]
    pub total_count: i64,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ClusterModelShare {
    #[serde(rename = "modelId")]
    pub model_id: String,
    pub occurrence: f64,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ClusterVerificationPair {
    #[serde(rename = "pairId")]
    pub pair_id: String,
    #[serde(rename = "snippetIdx")]
    pub snippet_idx: i64,
    #[serde(rename = "kbPath")]
    pub kb_path: String,
    pub quote: String,
    pub reasoning: String,
    #[serde(rename = "sourceUpdatedAt", default, skip_serializing_if = "Option::is_none")]
    pub source_updated_at: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ClusterVerificationPairsQuery {
    pub category_id: String,
    pub cluster_id: String,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ClusterVerificationPairsResponse {
    pub data: Vec<ClusterVerificationPair>,
    #[serde(rename = "clusterReasoning", default, skip_serializing_if = "Option::is_none")]
    pub cluster_reasoning: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FactCheckSetupStatusQuery {
    pub category_id: String,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct FactCheckSetupStatusResponse {
    #[serde(rename = "activeAccuracyPromptCount")]
    pub active_accuracy_prompt_count: i64,
    #[serde(rename = "hasVerificationData")]
    pub has_verification_data: bool,
    #[serde(rename = "isSetupComplete")]
    pub is_setup_complete: bool,
    #[serde(rename = "setupCreatedAt", default, skip_serializing_if = "Option::is_none")]
    pub setup_created_at: Option<String>,
    #[serde(rename = "setupKnowledgeBaseId", default, skip_serializing_if = "Option::is_none")]
    pub setup_knowledge_base_id: Option<String>,
}

/// A top inaccurate claim paired with one of its most-cited pages.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct InaccuracyDriverRow {
    #[serde(rename = "rowId")]
    pub row_id: String,
    #[serde(rename = "clusterId")]
    pub cluster_id: String,
    #[serde(rename = "canonicalClaim")]
    pub canonical_claim: String,
    pub snippet: String,
    #[serde(rename = "snippetClaimId")]
    pub snippet_claim_id: String,
    #[serde(rename = "claimOccurrence")]
    pub claim_occurrence: f64,
    #[serde(rename = "claimOccurrenceDelta", default, skip_serializing_if = "Option::is_none")]
    pub claim_occurrence_delta: Option<f64>,
    pub href: String,
    #[serde(rename = "citationCategory")]
    pub citation_category: String,
    #[serde(rename = "domainCategory")]
    pub domain_category: String,
    #[serde(rename = "citationCount")]
    pub citation_count: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct InaccuracyDriversQuery {
    pub start_date: String,
    pub end_date: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_start_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_end_date: Option<String>,
    pub category_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exclude_topic_ids: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_filter_type: Option<InaccuracyDriversQueryTagFilterType>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_tag: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub platform_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub persona_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_persona: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub citation_categories: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}

impl InaccuracyDriversQuery {
    /// Creates a new `InaccuracyDriversQuery` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `InaccuracyDriversQuery { comparison_start_date: Some(…), ..InaccuracyDriversQuery::new(…) }`.
    pub fn new(start_date: impl Into<String>, end_date: impl Into<String>, category_id: impl Into<String>) -> Self {
        Self {
            start_date: start_date.into(),
            end_date: end_date.into(),
            comparison_start_date: None,
            comparison_end_date: None,
            category_id: category_id.into(),
            topic_ids: None,
            exclude_topic_ids: None,
            tag_ids: None,
            tag_filter_type: None,
            include_no_tag: None,
            region_ids: None,
            platform_ids: None,
            persona_ids: None,
            include_no_persona: None,
            prompt_ids: None,
            citation_categories: None,
            limit: None,
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct InaccuracyDriversResponse {
    pub data: Vec<InaccuracyDriverRow>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct InaccurateClusterRow {
    #[serde(rename = "clusterId")]
    pub cluster_id: String,
    #[serde(rename = "canonicalClaim")]
    pub canonical_claim: String,
    #[serde(rename = "neutralTheme", default, skip_serializing_if = "Option::is_none")]
    pub neutral_theme: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "kbPath")]
    pub kb_path: String,
    #[serde(rename = "kbSnippet")]
    pub kb_snippet: String,
    pub reasoning: String,
    #[serde(rename = "claimCount")]
    pub claim_count: i64,
    #[serde(rename = "responseCount")]
    pub response_count: i64,
    #[serde(rename = "totalResponseCount")]
    pub total_response_count: i64,
    #[serde(rename = "responseShare")]
    pub response_share: f64,
    #[serde(rename = "responseShareDelta", default, skip_serializing_if = "Option::is_none")]
    pub response_share_delta: Option<f64>,
    #[serde(rename = "citationHostnames")]
    pub citation_hostnames: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub models: Option<Vec<ClusterModelShare>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct InaccurateClustersQuery {
    pub start_date: String,
    pub end_date: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_start_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_end_date: Option<String>,
    pub category_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exclude_topic_ids: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_filter_type: Option<InaccurateClustersQueryTagFilterType>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_tag: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub platform_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub persona_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_persona: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub citation_categories: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub theme_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub search_query: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_models: Option<bool>,
}

impl InaccurateClustersQuery {
    /// Creates a new `InaccurateClustersQuery` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `InaccurateClustersQuery { comparison_start_date: Some(…), ..InaccurateClustersQuery::new(…) }`.
    pub fn new(start_date: impl Into<String>, end_date: impl Into<String>, category_id: impl Into<String>) -> Self {
        Self {
            start_date: start_date.into(),
            end_date: end_date.into(),
            comparison_start_date: None,
            comparison_end_date: None,
            category_id: category_id.into(),
            topic_ids: None,
            exclude_topic_ids: None,
            tag_ids: None,
            tag_filter_type: None,
            include_no_tag: None,
            region_ids: None,
            platform_ids: None,
            persona_ids: None,
            include_no_persona: None,
            prompt_ids: None,
            citation_categories: None,
            theme_id: None,
            limit: None,
            offset: None,
            search_query: None,
            include_models: None,
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct InaccurateClustersResponse {
    pub data: Vec<InaccurateClusterRow>,
    #[serde(rename = "totalCount")]
    pub total_count: i64,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct InaccurateThemeRow {
    #[serde(rename = "themeId")]
    pub theme_id: String,
    #[serde(rename = "neutralTheme")]
    pub neutral_theme: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "inaccurateClaimCount")]
    pub inaccurate_claim_count: i64,
    #[serde(rename = "inaccurateClusterCount")]
    pub inaccurate_cluster_count: i64,
    #[serde(rename = "totalClaimCount")]
    pub total_claim_count: i64,
    #[serde(rename = "totalClusterCount")]
    pub total_cluster_count: i64,
    #[serde(rename = "responseCount")]
    pub response_count: i64,
    #[serde(rename = "totalResponseCount")]
    pub total_response_count: i64,
    #[serde(rename = "responseShare")]
    pub response_share: f64,
    #[serde(rename = "responseShareDelta", default, skip_serializing_if = "Option::is_none")]
    pub response_share_delta: Option<f64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct InaccurateThemesQuery {
    pub start_date: String,
    pub end_date: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_start_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_end_date: Option<String>,
    pub category_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exclude_topic_ids: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_filter_type: Option<InaccurateThemesQueryTagFilterType>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_tag: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub platform_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub persona_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_persona: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub citation_categories: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<InaccurateThemesQuerySortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub search_query: Option<String>,
}

impl InaccurateThemesQuery {
    /// Creates a new `InaccurateThemesQuery` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `InaccurateThemesQuery { comparison_start_date: Some(…), ..InaccurateThemesQuery::new(…) }`.
    pub fn new(start_date: impl Into<String>, end_date: impl Into<String>, category_id: impl Into<String>) -> Self {
        Self {
            start_date: start_date.into(),
            end_date: end_date.into(),
            comparison_start_date: None,
            comparison_end_date: None,
            category_id: category_id.into(),
            topic_ids: None,
            exclude_topic_ids: None,
            tag_ids: None,
            tag_filter_type: None,
            include_no_tag: None,
            region_ids: None,
            platform_ids: None,
            persona_ids: None,
            include_no_persona: None,
            prompt_ids: None,
            citation_categories: None,
            limit: None,
            offset: None,
            sort_by: None,
            sort_order: None,
            search_query: None,
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct InaccurateThemesResponse {
    pub data: Vec<InaccurateThemeRow>,
    #[serde(rename = "totalCount")]
    pub total_count: i64,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TopInaccurateClaimRow {
    #[serde(rename = "clusterId")]
    pub cluster_id: String,
    #[serde(rename = "canonicalClaim")]
    pub canonical_claim: String,
    #[serde(rename = "claimOccurrence")]
    pub claim_occurrence: f64,
    #[serde(rename = "claimOccurrenceDelta", default, skip_serializing_if = "Option::is_none")]
    pub claim_occurrence_delta: Option<f64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TopInaccurateClaimsQuery {
    pub start_date: String,
    pub end_date: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_start_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comparison_end_date: Option<String>,
    pub category_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exclude_topic_ids: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tag_filter_type: Option<TopInaccurateClaimsQueryTagFilterType>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_tag: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub platform_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub persona_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_no_persona: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_ids: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub citation_categories: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}

impl TopInaccurateClaimsQuery {
    /// Creates a new `TopInaccurateClaimsQuery` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `TopInaccurateClaimsQuery { comparison_start_date: Some(…), ..TopInaccurateClaimsQuery::new(…) }`.
    pub fn new(start_date: impl Into<String>, end_date: impl Into<String>, category_id: impl Into<String>) -> Self {
        Self {
            start_date: start_date.into(),
            end_date: end_date.into(),
            comparison_start_date: None,
            comparison_end_date: None,
            category_id: category_id.into(),
            topic_ids: None,
            exclude_topic_ids: None,
            tag_ids: None,
            tag_filter_type: None,
            include_no_tag: None,
            region_ids: None,
            platform_ids: None,
            persona_ids: None,
            include_no_persona: None,
            prompt_ids: None,
            citation_categories: None,
            limit: None,
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TopInaccurateClaimsResponse {
    pub data: Vec<TopInaccurateClaimRow>,
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum AccuracyBreakdownQueryTagFilterType {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "any")]
    Any,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl AccuracyBreakdownQueryTagFilterType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::All => "all",
            Self::Any => "any",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for AccuracyBreakdownQueryTagFilterType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for AccuracyBreakdownQueryTagFilterType {
    fn from(value: &str) -> Self {
        match value {
            "all" => Self::All,
            "any" => Self::Any,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum AccuracyBreakdownQueryBreakdownBy {
    #[serde(rename = "citation")]
    Citation,
    #[serde(rename = "platform")]
    Platform,
    #[serde(rename = "topic")]
    Topic,
    #[serde(rename = "prompt")]
    Prompt,
    #[serde(rename = "tag")]
    Tag,
    #[serde(rename = "region")]
    Region,
    #[serde(rename = "persona")]
    Persona,
    #[serde(rename = "theme")]
    Theme,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl AccuracyBreakdownQueryBreakdownBy {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Citation => "citation",
            Self::Platform => "platform",
            Self::Topic => "topic",
            Self::Prompt => "prompt",
            Self::Tag => "tag",
            Self::Region => "region",
            Self::Persona => "persona",
            Self::Theme => "theme",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for AccuracyBreakdownQueryBreakdownBy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for AccuracyBreakdownQueryBreakdownBy {
    fn from(value: &str) -> Self {
        match value {
            "citation" => Self::Citation,
            "platform" => Self::Platform,
            "topic" => Self::Topic,
            "prompt" => Self::Prompt,
            "tag" => Self::Tag,
            "region" => Self::Region,
            "persona" => Self::Persona,
            "theme" => Self::Theme,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum AccuracyBreakdownQueryGroupBy {
    #[serde(rename = "platform")]
    Platform,
    #[serde(rename = "topic")]
    Topic,
    #[serde(rename = "prompt")]
    Prompt,
    #[serde(rename = "tag")]
    Tag,
    #[serde(rename = "region")]
    Region,
    #[serde(rename = "persona")]
    Persona,
    #[serde(rename = "theme")]
    Theme,
    #[serde(rename = "date")]
    Date,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl AccuracyBreakdownQueryGroupBy {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Platform => "platform",
            Self::Topic => "topic",
            Self::Prompt => "prompt",
            Self::Tag => "tag",
            Self::Region => "region",
            Self::Persona => "persona",
            Self::Theme => "theme",
            Self::Date => "date",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for AccuracyBreakdownQueryGroupBy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for AccuracyBreakdownQueryGroupBy {
    fn from(value: &str) -> Self {
        match value {
            "platform" => Self::Platform,
            "topic" => Self::Topic,
            "prompt" => Self::Prompt,
            "tag" => Self::Tag,
            "region" => Self::Region,
            "persona" => Self::Persona,
            "theme" => Self::Theme,
            "date" => Self::Date,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum AccuracyBreakdownQuerySortBy {
    #[serde(rename = "citationShare")]
    CitationShare,
    #[serde(rename = "accuracy")]
    Accuracy,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl AccuracyBreakdownQuerySortBy {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::CitationShare => "citationShare",
            Self::Accuracy => "accuracy",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for AccuracyBreakdownQuerySortBy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for AccuracyBreakdownQuerySortBy {
    fn from(value: &str) -> Self {
        match value {
            "citationShare" => Self::CitationShare,
            "accuracy" => Self::Accuracy,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum AccuracyBreakdownQuerySortOrder {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl AccuracyBreakdownQuerySortOrder {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Asc => "asc",
            Self::Desc => "desc",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for AccuracyBreakdownQuerySortOrder {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for AccuracyBreakdownQuerySortOrder {
    fn from(value: &str) -> Self {
        match value {
            "asc" => Self::Asc,
            "desc" => Self::Desc,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum AccuracyCitationClaimPolarity {
    #[serde(rename = "positive")]
    Positive,
    #[serde(rename = "negative")]
    Negative,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl AccuracyCitationClaimPolarity {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Positive => "positive",
            Self::Negative => "negative",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for AccuracyCitationClaimPolarity {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for AccuracyCitationClaimPolarity {
    fn from(value: &str) -> Self {
        match value {
            "positive" => Self::Positive,
            "negative" => Self::Negative,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum AccuracyOverviewQueryTagFilterType {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "any")]
    Any,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl AccuracyOverviewQueryTagFilterType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::All => "all",
            Self::Any => "any",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for AccuracyOverviewQueryTagFilterType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for AccuracyOverviewQueryTagFilterType {
    fn from(value: &str) -> Self {
        match value {
            "all" => Self::All,
            "any" => Self::Any,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum AccuracyOverviewQueryGroupBy {
    #[serde(rename = "period")]
    Period,
    #[serde(rename = "theme")]
    Theme,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl AccuracyOverviewQueryGroupBy {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Period => "period",
            Self::Theme => "theme",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for AccuracyOverviewQueryGroupBy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for AccuracyOverviewQueryGroupBy {
    fn from(value: &str) -> Self {
        match value {
            "period" => Self::Period,
            "theme" => Self::Theme,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum AccuracyPaginationMetric {
    #[serde(rename = "accuracy")]
    Accuracy,
    #[serde(rename = "inaccurate_claims")]
    InaccurateClaims,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl AccuracyPaginationMetric {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Accuracy => "accuracy",
            Self::InaccurateClaims => "inaccurate_claims",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for AccuracyPaginationMetric {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for AccuracyPaginationMetric {
    fn from(value: &str) -> Self {
        match value {
            "accuracy" => Self::Accuracy,
            "inaccurate_claims" => Self::InaccurateClaims,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum AccuracyPaginationMode {
    #[serde(rename = "current")]
    Current,
    #[serde(rename = "delta")]
    Delta,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl AccuracyPaginationMode {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Current => "current",
            Self::Delta => "delta",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for AccuracyPaginationMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for AccuracyPaginationMode {
    fn from(value: &str) -> Self {
        match value {
            "current" => Self::Current,
            "delta" => Self::Delta,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum AccuracyPaginationDirection {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl AccuracyPaginationDirection {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Asc => "asc",
            Self::Desc => "desc",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for AccuracyPaginationDirection {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for AccuracyPaginationDirection {
    fn from(value: &str) -> Self {
        match value {
            "asc" => Self::Asc,
            "desc" => Self::Desc,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ClaimBreakdownQueryTagFilterType {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "any")]
    Any,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ClaimBreakdownQueryTagFilterType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::All => "all",
            Self::Any => "any",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ClaimBreakdownQueryTagFilterType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ClaimBreakdownQueryTagFilterType {
    fn from(value: &str) -> Self {
        match value {
            "all" => Self::All,
            "any" => Self::Any,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ClaimCitationsQueryTagFilterType {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "any")]
    Any,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ClaimCitationsQueryTagFilterType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::All => "all",
            Self::Any => "any",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ClaimCitationsQueryTagFilterType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ClaimCitationsQueryTagFilterType {
    fn from(value: &str) -> Self {
        match value {
            "all" => Self::All,
            "any" => Self::Any,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ClaimCitationsQuerySortOrder {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ClaimCitationsQuerySortOrder {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Asc => "asc",
            Self::Desc => "desc",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ClaimCitationsQuerySortOrder {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ClaimCitationsQuerySortOrder {
    fn from(value: &str) -> Self {
        match value {
            "asc" => Self::Asc,
            "desc" => Self::Desc,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ClusterExampleRunsQueryTagFilterType {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "any")]
    Any,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ClusterExampleRunsQueryTagFilterType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::All => "all",
            Self::Any => "any",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ClusterExampleRunsQueryTagFilterType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ClusterExampleRunsQueryTagFilterType {
    fn from(value: &str) -> Self {
        match value {
            "all" => Self::All,
            "any" => Self::Any,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum InaccuracyDriversQueryTagFilterType {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "any")]
    Any,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl InaccuracyDriversQueryTagFilterType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::All => "all",
            Self::Any => "any",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for InaccuracyDriversQueryTagFilterType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for InaccuracyDriversQueryTagFilterType {
    fn from(value: &str) -> Self {
        match value {
            "all" => Self::All,
            "any" => Self::Any,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum InaccurateClustersQueryTagFilterType {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "any")]
    Any,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl InaccurateClustersQueryTagFilterType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::All => "all",
            Self::Any => "any",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for InaccurateClustersQueryTagFilterType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for InaccurateClustersQueryTagFilterType {
    fn from(value: &str) -> Self {
        match value {
            "all" => Self::All,
            "any" => Self::Any,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum InaccurateThemesQueryTagFilterType {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "any")]
    Any,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl InaccurateThemesQueryTagFilterType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::All => "all",
            Self::Any => "any",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for InaccurateThemesQueryTagFilterType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for InaccurateThemesQueryTagFilterType {
    fn from(value: &str) -> Self {
        match value {
            "all" => Self::All,
            "any" => Self::Any,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum InaccurateThemesQuerySortOrder {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl InaccurateThemesQuerySortOrder {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Asc => "asc",
            Self::Desc => "desc",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for InaccurateThemesQuerySortOrder {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for InaccurateThemesQuerySortOrder {
    fn from(value: &str) -> Self {
        match value {
            "asc" => Self::Asc,
            "desc" => Self::Desc,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum TopInaccurateClaimsQueryTagFilterType {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "any")]
    Any,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl TopInaccurateClaimsQueryTagFilterType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::All => "all",
            Self::Any => "any",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for TopInaccurateClaimsQueryTagFilterType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for TopInaccurateClaimsQueryTagFilterType {
    fn from(value: &str) -> Self {
        match value {
            "all" => Self::All,
            "any" => Self::Any,
            other => Self::Unknown(other.to_owned()),
        }
    }
}
