// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `ad_account`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

/// One insights row; the entity it describes follows `aggregation_level`.
///
/// Time bounds are present when a `time_granularity` is requested (one row per
/// time bucket); the entity id/name fields (`campaign_*`, `ad_group_*`, `ad_*`)
/// are present when rows are broken down by that entity.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct InsightRow {
    /// Row ID.
    pub id: String,
    /// Bucket start (unix seconds).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub start_time: Option<i64>,
    /// Bucket end (unix seconds).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_time: Option<i64>,
    /// Human-readable time bucket.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub readable_time: Option<String>,
    /// Timezone of the time bucket.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Campaign ID for campaign-level rows.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub campaign_id: Option<String>,
    /// Campaign name for campaign-level rows.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub campaign_name: Option<String>,
    /// Ad group ID for ad_group-level rows.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ad_group_id: Option<String>,
    /// Ad group name for ad_group-level rows.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ad_group_name: Option<String>,
    /// Ad ID for ad-level rows.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ad_id: Option<String>,
    /// Ad name for ad-level rows.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ad_name: Option<String>,
    /// Impressions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub impressions: Option<i64>,
    /// Clicks.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub clicks: Option<i64>,
    /// Spend in the ad account's currency units.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spend: Option<f64>,
    /// Click-through rate.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ctr: Option<f64>,
    /// Cost per click.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpc: Option<f64>,
    /// Cost per thousand impressions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpm: Option<f64>,
}

/// Cursor-paginated insights, mirroring the OpenAI Ads insights envelope.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct InsightsResponse {
    /// Insight rows.
    pub data: Vec<InsightRow>,
    /// Total row count, when reported upstream.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// ID of the first item; pass as `before` to page back.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub first_id: Option<String>,
    /// ID of the last item; pass as `after` to page forward.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_id: Option<String>,
    /// Whether more items are available.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
}
