// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `integrations`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

/// One connected integration installation visible to the caller.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Integration {
    /// Installation id to bind to a hub-backed node's `integration_id`.
    pub id: String,
    /// Canonical connector id, matching node contracts.
    pub provider: String,
    /// Human-readable account label for the connection.
    pub label: String,
    /// Connected account identity as the provider reports it, e.g. the Google account email or the WordPress site URL. This is what tells two connections of the same provider apart; `label` often repeats across them. Null when the provider reports no identity.
    #[serde(default)]
    pub account: Option<String>,
    /// Connection lifecycle status.
    pub status: String,
    /// Installation scope: shared across the org, or user-owned.
    pub level: IntegrationLevel,
}

/// Connected integrations visible to the caller's org/user context.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct IntegrationsResponse {
    /// Connected integrations.
    pub data: Vec<Integration>,
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum IntegrationLevel {
    #[serde(rename = "org")]
    Org,
    #[serde(rename = "user")]
    User,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl IntegrationLevel {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Org => "org",
            Self::User => "user",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for IntegrationLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for IntegrationLevel {
    fn from(value: &str) -> Self {
        match value {
            "org" => Self::Org,
            "user" => Self::User,
            other => Self::Unknown(other.to_owned()),
        }
    }
}
