// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `intents`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

/// Intent share averaged across the requested cohort date range.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct OtfIntentShareData {
    pub main_classification: String,
    #[serde(default)]
    pub sub_category_classification: Option<String>,
    #[serde(serialize_with = "crate::number::serialize")]
    pub pct_conversation: f64,
}

/// Query for on-the-fly intent shares for a single keyword.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct OtfIntentSharesQuery {
    pub keyword: String,
    pub matching_type: OtfIntentSharesQueryMatchingType,
    pub start_date: chrono::NaiveDate,
    pub end_date: chrono::NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub regions: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub platforms: Option<Vec<String>>,
}

impl OtfIntentSharesQuery {
    /// Creates a new `OtfIntentSharesQuery` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `OtfIntentSharesQuery { regions: Some(…), ..OtfIntentSharesQuery::new(…) }`.
    pub fn new(
        keyword: impl Into<String>,
        matching_type: OtfIntentSharesQueryMatchingType,
        start_date: chrono::NaiveDate,
        end_date: chrono::NaiveDate,
    ) -> Self {
        Self {
            keyword: keyword.into(),
            matching_type,
            start_date,
            end_date,
            regions: None,
            platforms: None,
        }
    }
}

/// Response wrapper for on-the-fly intent shares.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct OtfIntentSharesResponse {
    /// Metadata for volume query response.
    /// truncated indicates if results hit MAX_ROWS limit.
    pub info: VolumeResponseInfo,
    pub data: Vec<OtfIntentShareData>,
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum OtfIntentSharesQueryMatchingType {
    #[serde(rename = "exact_match")]
    ExactMatch,
    #[serde(rename = "phrase_match")]
    PhraseMatch,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl OtfIntentSharesQueryMatchingType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::ExactMatch => "exact_match",
            Self::PhraseMatch => "phrase_match",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for OtfIntentSharesQueryMatchingType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for OtfIntentSharesQueryMatchingType {
    fn from(value: &str) -> Self {
        match value {
            "exact_match" => Self::ExactMatch,
            "phrase_match" => Self::PhraseMatch,
            other => Self::Unknown(other.to_owned()),
        }
    }
}
