// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `knowledge_bases_documents`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DeleteDocumentRequest {
    /// Document path to delete.
    pub name: String,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DocumentOperationResponse {
    /// Operation result message.
    pub message: String,
    /// Document name.
    pub name: String,
    /// Document path.
    pub path: String,
    /// Document folder path.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub folder: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DocumentsCreateBody {
    /// Unique document name.
    pub name: String,
    /// Text content to add to the document.
    pub text: String,
    /// Folder path to add the document under.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub folder: Option<String>,
}

impl DocumentsCreateBody {
    /// Creates a new `DocumentsCreateBody` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `DocumentsCreateBody { folder: Some(…), ..DocumentsCreateBody::new(name, text) }`.
    pub fn new(name: impl Into<String>, text: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            text: text.into(),
            folder: None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DocumentsUpdateBody {
    /// Document name or path to update.
    pub name: String,
    /// Replacement text content for the document.
    pub text: String,
    /// Folder path containing the document.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub folder: Option<String>,
}

impl DocumentsUpdateBody {
    /// Creates a new `DocumentsUpdateBody` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `DocumentsUpdateBody { folder: Some(…), ..DocumentsUpdateBody::new(name, text) }`.
    pub fn new(name: impl Into<String>, text: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            text: text.into(),
            folder: None,
        }
    }
}
