// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `optimization`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AeoScore {
    pub target_zone: AeoScoreTargetZone,
    pub value: f64,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AeoScoreTargetZone {
    pub low: f64,
    pub high: f64,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AnalysisBreakdown {
    pub title: String,
    pub weight: f64,
    pub score: f64,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AnalysisInputs {
    #[serde(default)]
    pub topic: Option<TopicInput>,
    #[serde(default)]
    pub prompt: Option<PromptInput>,
    pub top_citations: Vec<String>,
    pub user: UserInput,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AnalysisSummary {
    pub breakdown: Vec<AnalysisBreakdown>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ContentAnalysis {
    pub content: DocumentContent,
    #[serde(default)]
    pub aeo_content_score: Option<AeoScore>,
    pub analysis: AnalysisSummary,
    pub recommendations: Vec<Recommendation>,
    pub inputs: AnalysisInputs,
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ContentFormat {
    #[serde(rename = "markdown")]
    Markdown,
    #[serde(rename = "html")]
    Html,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ContentFormat {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Markdown => "markdown",
            Self::Html => "html",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ContentFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ContentFormat {
    fn from(value: &str) -> Self {
        match value {
            "markdown" => Self::Markdown,
            "html" => Self::Html,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ContentOptimization {
    pub id: String,
    pub title: String,
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(default)]
    pub extracted_input: Option<String>,
    pub r#type: ContentType,
    pub status: String,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ContentOptimizationAnalysisResponse {
    pub data: ContentAnalysis,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ContentOptimizationResponse {
    pub info: ContentOptimizationResponseInfo,
    pub data: Vec<ContentOptimization>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ContentOptimizationResponseInfo {
    pub total_rows: i64,
    pub query: OptimizationQuery,
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ContentType {
    #[serde(rename = "file")]
    File,
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "url")]
    Url,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ContentType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::File => "file",
            Self::Text => "text",
            Self::Url => "url",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ContentType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ContentType {
    fn from(value: &str) -> Self {
        match value {
            "file" => Self::File,
            "text" => Self::Text,
            "url" => Self::Url,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct DocumentContent {
    pub format: ContentFormat,
    pub value: String,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct OptimizationQuery {
    pub asset_id: String,
    /// Pagination parameters for the results. Default is 10,000 rows with no offset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Pagination>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct PromptInput {
    pub id: String,
    pub name: String,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Recommendation {
    pub title: String,
    pub status: RecommendationStatus,
    #[serde(default)]
    pub impact: Option<RecommendationImpact>,
    pub suggestion: RecommendationSuggestion,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct RecommendationImpact {
    pub section: String,
    pub score: f64,
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum RecommendationStatus {
    #[serde(rename = "done")]
    Done,
    #[serde(rename = "pending")]
    Pending,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl RecommendationStatus {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Done => "done",
            Self::Pending => "pending",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for RecommendationStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for RecommendationStatus {
    fn from(value: &str) -> Self {
        match value {
            "done" => Self::Done,
            "pending" => Self::Pending,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct RecommendationSuggestion {
    pub text: String,
    pub rationale: String,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TopicInput {
    pub id: String,
    pub name: String,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct UserInput {
    pub r#type: ContentType,
    pub value: String,
    pub metadata: std::collections::HashMap<String, UserInputMetadata>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
#[non_exhaustive]
pub enum UserInputMetadata {
    Variant1(i64),
    Variant2(String),
    /// A variant not recognized by this version of the SDK, preserved verbatim.
    ///
    /// Match the specific variants first. Matching this one directly is an
    /// anti-pattern: that arm silently stops matching once a future SDK
    /// release adds the real variant.
    #[serde(untagged)]
    Unknown(serde_json::Value),
}
