// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `shopping`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct BrandNameFilter {
    #[serde(default, skip_serializing)]
    pub field: String,
    pub operator: BrandNameFilterOperator,
    pub value: BrandNameFilterValue,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct MerchantNameFilter {
    #[serde(default, skip_serializing)]
    pub field: String,
    pub operator: MerchantNameFilterOperator,
    pub value: MerchantNameFilterValue,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ProductNameFilter {
    #[serde(default, skip_serializing)]
    pub field: String,
    pub operator: ProductNameFilterOperator,
    pub value: ProductNameFilterValue,
}

/// One (asset x group) row. Group dims/metrics present depend on `group_by`/`metrics`.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ShoppingBrandRow {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asset: Option<serde_json::Value>,
    /// Asset visibility rank as a top-level field (ungrouped only).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rank: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic: Option<DimensionRef>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region: Option<DimensionRef>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt: Option<DimensionRef>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visibility_score: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub average_position: Option<f64>,
    /// Asset visibility rank (present on grouped rows).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visibility_rank: Option<i64>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ShoppingBrandsV2Info {
    /// Total assets matching the query before pagination.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_results: Option<i64>,
    /// Number of assets on this page. When grouped by `date`, `data` holds one row per asset x bucket, so `len(data)` can exceed `count`.
    pub count: i64,
    /// Opaque cursor for the next page; null on the last page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    /// Display names of the models the report covers.
    pub models: Vec<String>,
    /// Echoed request start date (YYYY-MM-DD, ET).
    pub start_date: String,
    /// Echoed request end date (YYYY-MM-DD, ET).
    pub end_date: String,
    /// Echoed normalized filter tree, or null when no filter was sent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<serde_json::Value>,
    /// Asset scope: `all`, `owned`, or `custom` when `assets` was given.
    pub scope: String,
    /// Echoed `assets` selection; when set it overrides `scope`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub assets: Option<ShoppingBrandsV2InfoAssets>,
    /// Metrics returned per row.
    pub metrics: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ShoppingBrandsV2Query {
    pub category_id: String,
    /// YYYY-MM-DD, ET, inclusive
    pub start_date: String,
    /// YYYY-MM-DD, ET, inclusive
    pub end_date: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_by: Option<Vec<ShoppingBrandsV2QueryGroupBy>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Vec<ShoppingBrandsV2QueryMetric>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interval: Option<ShoppingBrandsV2QueryInterval>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scope: Option<ShoppingBrandsV2QueryScope>,
    /// Restrict to these asset names (a name or list). Overrides `scope`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub assets: Option<ShoppingBrandsV2QueryAssets>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<FilterNode>,
    /// Page size for scope=all; default 10, max 50.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Stream endpoint only: cap the number of streamed rows (default: all).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_results: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl ShoppingBrandsV2Query {
    /// Creates a new `ShoppingBrandsV2Query` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `ShoppingBrandsV2Query { group_by: Some(…), ..ShoppingBrandsV2Query::new(category_id, start_date, end_date) }`.
    pub fn new(category_id: impl Into<String>, start_date: impl Into<String>, end_date: impl Into<String>) -> Self {
        Self {
            category_id: category_id.into(),
            start_date: start_date.into(),
            end_date: end_date.into(),
            group_by: None,
            metrics: None,
            interval: None,
            scope: None,
            assets: None,
            filter: None,
            limit: None,
            max_results: None,
            cursor: None,
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ShoppingBrandsV2Response {
    pub info: ShoppingBrandsV2Info,
    pub data: Vec<ShoppingBrandRow>,
}

/// One merchant row. `brand_name`/`brand_share` appear in the brand-share view; `product`/product
/// metrics in the top-products view; metrics vary by view.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ShoppingMerchantRow {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub merchant_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub merchant_share: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub merchant_share_rank: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub merchant_visibility: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub merchant_visibility_rank: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visibility_rank: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub brand_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub brand_share: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub product: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub product_visibility: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub product_rank: Option<i64>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ShoppingMerchantsV2Info {
    /// Total rows matching the query before pagination (null when not computed).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_results: Option<i64>,
    /// Number of rows returned in `data` for this page.
    pub count: i64,
    /// Opaque cursor for the next page; null on the last page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    /// Display names of the models the report covers.
    pub models: Vec<String>,
    /// Echoed request start date (YYYY-MM-DD, ET).
    pub start_date: String,
    /// Echoed request end date (YYYY-MM-DD, ET).
    pub end_date: String,
    /// Echoed normalized filter tree, or null when no filter was sent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<serde_json::Value>,
    /// `distribution`, `brand_share`, or `top_products`.
    pub view: String,
    /// Metrics returned per row.
    pub metrics: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ShoppingMerchantsV2Query {
    pub category_id: String,
    /// YYYY-MM-DD, ET, inclusive
    pub start_date: String,
    /// YYYY-MM-DD, ET, inclusive
    pub end_date: String,
    /// `[]` = distribution; `[brand]` = brand share within each merchant; `[product]` = top products per merchant. `date` (distribution only) adds a time series.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_by: Option<Vec<ShoppingMerchantsV2QueryGroupBy>>,
    /// Defaults to the chosen view's metrics; must be valid for that view.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Vec<ShoppingMerchantsV2QueryMetric>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interval: Option<ShoppingMerchantsV2QueryInterval>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<FilterNode>,
    /// Page size; default 10, max 50.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Stream endpoint only: cap streamed rows.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_results: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl ShoppingMerchantsV2Query {
    /// Creates a new `ShoppingMerchantsV2Query` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `ShoppingMerchantsV2Query { group_by: Some(…), ..ShoppingMerchantsV2Query::new(…) }`.
    pub fn new(category_id: impl Into<String>, start_date: impl Into<String>, end_date: impl Into<String>) -> Self {
        Self {
            category_id: category_id.into(),
            start_date: start_date.into(),
            end_date: end_date.into(),
            group_by: None,
            metrics: None,
            interval: None,
            filter: None,
            limit: None,
            max_results: None,
            cursor: None,
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ShoppingMerchantsV2Response {
    pub info: ShoppingMerchantsV2Info,
    pub data: Vec<ShoppingMerchantRow>,
}

/// One product row. Merchant fields present only when `include_merchants` is true.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ShoppingProductRow {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub product: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic: Option<DimensionRef>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt: Option<DimensionRef>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visibility_score: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub average_position: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visibility_rank: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub position1_percentage: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub position2_percentage: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub position3_percentage: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub position_above3_percentage: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub product_rating: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub product_num_reviews: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub product_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub product_image_urls: Option<Vec<String>>,
    /// Per-product merchant offers `{name, price}` (only with `include_merchants`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub merchants: Option<Vec<serde_json::Value>>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ShoppingProductsV2Info {
    /// Total products matching the query before pagination.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_results: Option<i64>,
    /// Number of products on this page. When grouped by `date`/`topic`/`prompt`, `data` holds one row per product x bucket, so `len(data)` can exceed `count`.
    pub count: i64,
    /// Opaque cursor for the next page; null on the last page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    /// Display names of the models the report covers.
    pub models: Vec<String>,
    /// Echoed request start date (YYYY-MM-DD, ET).
    pub start_date: String,
    /// Echoed request end date (YYYY-MM-DD, ET).
    pub end_date: String,
    /// Echoed normalized filter tree, or null when no filter was sent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<serde_json::Value>,
    /// Whether merchant offers are included in each row.
    pub include_merchants: bool,
    /// Metrics returned per row.
    pub metrics: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ShoppingProductsV2Query {
    pub category_id: String,
    /// YYYY-MM-DD, ET, inclusive
    pub start_date: String,
    /// YYYY-MM-DD, ET, inclusive
    pub end_date: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_by: Option<Vec<ShoppingProductsV2QueryGroupBy>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Vec<ShoppingProductsV2QueryMetric>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interval: Option<ShoppingProductsV2QueryInterval>,
    /// Include per-product merchant offers (names, prices, urls, images).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_merchants: Option<bool>,
    /// Return this product plus its top competitors (item view only).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target_product: Option<String>,
    /// Competitors returned when `target_product` is set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub competitor_limit: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<FilterNode>,
    /// Page size; default 10, max 50.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Stream endpoint only: cap streamed rows.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_results: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl ShoppingProductsV2Query {
    /// Creates a new `ShoppingProductsV2Query` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `ShoppingProductsV2Query { group_by: Some(…), ..ShoppingProductsV2Query::new(…) }`.
    pub fn new(category_id: impl Into<String>, start_date: impl Into<String>, end_date: impl Into<String>) -> Self {
        Self {
            category_id: category_id.into(),
            start_date: start_date.into(),
            end_date: end_date.into(),
            group_by: None,
            metrics: None,
            interval: None,
            include_merchants: None,
            target_product: None,
            competitor_limit: None,
            filter: None,
            limit: None,
            max_results: None,
            cursor: None,
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ShoppingProductsV2Response {
    pub info: ShoppingProductsV2Info,
    pub data: Vec<ShoppingProductRow>,
}

/// One trigger-rate row. Group dims present depend on `group_by`.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ShoppingTriggerRateRow {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic: Option<DimensionRef>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region: Option<DimensionRef>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub persona: Option<DimensionRef>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt: Option<DimensionRef>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_runs: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shopping_triggered_runs: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trigger_rate_percentage: Option<f64>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ShoppingTriggerRateV2Info {
    /// Total rows matching the query before pagination (null when not computed).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_results: Option<i64>,
    /// Number of rows returned in `data` for this page.
    pub count: i64,
    /// Opaque cursor for the next page; null on the last page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    /// Display names of the models the report covers.
    pub models: Vec<String>,
    /// Echoed request start date (YYYY-MM-DD, ET).
    pub start_date: String,
    /// Echoed request end date (YYYY-MM-DD, ET).
    pub end_date: String,
    /// Echoed normalized filter tree, or null when no filter was sent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<serde_json::Value>,
    /// Metrics returned per row.
    pub metrics: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ShoppingTriggerRateV2Query {
    pub category_id: String,
    /// YYYY-MM-DD, ET, inclusive
    pub start_date: String,
    /// YYYY-MM-DD, ET, inclusive
    pub end_date: String,
    /// Group by `prompt`/`topic` for the per-prompt/-topic trigger rate.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_by: Option<Vec<ShoppingTriggerRateV2QueryGroupBy>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Vec<ShoppingTriggerRateV2QueryMetric>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interval: Option<ShoppingTriggerRateV2QueryInterval>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<FilterNode>,
    /// Page size; default 10, max 50.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Stream endpoint only: cap streamed rows.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_results: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl ShoppingTriggerRateV2Query {
    /// Creates a new `ShoppingTriggerRateV2Query` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `ShoppingTriggerRateV2Query { group_by: Some(…), ..ShoppingTriggerRateV2Query::new(…) }`.
    pub fn new(category_id: impl Into<String>, start_date: impl Into<String>, end_date: impl Into<String>) -> Self {
        Self {
            category_id: category_id.into(),
            start_date: start_date.into(),
            end_date: end_date.into(),
            group_by: None,
            metrics: None,
            interval: None,
            filter: None,
            limit: None,
            max_results: None,
            cursor: None,
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ShoppingTriggerRateV2Response {
    pub info: ShoppingTriggerRateV2Info,
    pub data: Vec<ShoppingTriggerRateRow>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
#[non_exhaustive]
pub enum ShoppingStreamBrandsResponse {
    ShoppingBrandsV2Info(ShoppingBrandsV2Info),
    ShoppingBrandRow(ShoppingBrandRow),
    /// A variant not recognized by this version of the SDK, preserved verbatim.
    ///
    /// Match the specific variants first. Matching this one directly is an
    /// anti-pattern: that arm silently stops matching once a future SDK
    /// release adds the real variant.
    #[serde(untagged)]
    Unknown(serde_json::Value),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
#[non_exhaustive]
pub enum ShoppingStreamProductsResponse {
    ShoppingProductsV2Info(ShoppingProductsV2Info),
    ShoppingProductRow(ShoppingProductRow),
    /// A variant not recognized by this version of the SDK, preserved verbatim.
    ///
    /// Match the specific variants first. Matching this one directly is an
    /// anti-pattern: that arm silently stops matching once a future SDK
    /// release adds the real variant.
    #[serde(untagged)]
    Unknown(serde_json::Value),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
#[non_exhaustive]
pub enum ShoppingStreamMerchantsResponse {
    ShoppingMerchantsV2Info(ShoppingMerchantsV2Info),
    ShoppingMerchantRow(ShoppingMerchantRow),
    /// A variant not recognized by this version of the SDK, preserved verbatim.
    ///
    /// Match the specific variants first. Matching this one directly is an
    /// anti-pattern: that arm silently stops matching once a future SDK
    /// release adds the real variant.
    #[serde(untagged)]
    Unknown(serde_json::Value),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
#[non_exhaustive]
pub enum ShoppingStreamTriggerRateResponse {
    ShoppingTriggerRateV2Info(ShoppingTriggerRateV2Info),
    ShoppingTriggerRateRow(ShoppingTriggerRateRow),
    /// A variant not recognized by this version of the SDK, preserved verbatim.
    ///
    /// Match the specific variants first. Matching this one directly is an
    /// anti-pattern: that arm silently stops matching once a future SDK
    /// release adds the real variant.
    #[serde(untagged)]
    Unknown(serde_json::Value),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
#[non_exhaustive]
pub enum ShoppingBrandsV2InfoAssets {
    Variant2(Vec<String>),
    Variant1(String),
    /// A variant not recognized by this version of the SDK, preserved verbatim.
    ///
    /// Match the specific variants first. Matching this one directly is an
    /// anti-pattern: that arm silently stops matching once a future SDK
    /// release adds the real variant.
    #[serde(untagged)]
    Unknown(serde_json::Value),
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ShoppingBrandsV2QueryGroupBy {
    #[serde(rename = "date")]
    Date,
    #[serde(rename = "topic")]
    Topic,
    #[serde(rename = "region")]
    Region,
    #[serde(rename = "prompt")]
    Prompt,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ShoppingBrandsV2QueryGroupBy {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Date => "date",
            Self::Topic => "topic",
            Self::Region => "region",
            Self::Prompt => "prompt",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ShoppingBrandsV2QueryGroupBy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ShoppingBrandsV2QueryGroupBy {
    fn from(value: &str) -> Self {
        match value {
            "date" => Self::Date,
            "topic" => Self::Topic,
            "region" => Self::Region,
            "prompt" => Self::Prompt,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ShoppingBrandsV2QueryMetric {
    #[serde(rename = "visibility_score")]
    VisibilityScore,
    #[serde(rename = "average_position")]
    AveragePosition,
    #[serde(rename = "visibility_rank")]
    VisibilityRank,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ShoppingBrandsV2QueryMetric {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::VisibilityScore => "visibility_score",
            Self::AveragePosition => "average_position",
            Self::VisibilityRank => "visibility_rank",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ShoppingBrandsV2QueryMetric {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ShoppingBrandsV2QueryMetric {
    fn from(value: &str) -> Self {
        match value {
            "visibility_score" => Self::VisibilityScore,
            "average_position" => Self::AveragePosition,
            "visibility_rank" => Self::VisibilityRank,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ShoppingBrandsV2QueryInterval {
    #[serde(rename = "day")]
    Day,
    #[serde(rename = "week")]
    Week,
    #[serde(rename = "month")]
    Month,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ShoppingBrandsV2QueryInterval {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Day => "day",
            Self::Week => "week",
            Self::Month => "month",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ShoppingBrandsV2QueryInterval {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ShoppingBrandsV2QueryInterval {
    fn from(value: &str) -> Self {
        match value {
            "day" => Self::Day,
            "week" => Self::Week,
            "month" => Self::Month,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ShoppingBrandsV2QueryScope {
    #[serde(rename = "owned")]
    Owned,
    #[serde(rename = "all")]
    All,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ShoppingBrandsV2QueryScope {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Owned => "owned",
            Self::All => "all",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ShoppingBrandsV2QueryScope {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ShoppingBrandsV2QueryScope {
    fn from(value: &str) -> Self {
        match value {
            "owned" => Self::Owned,
            "all" => Self::All,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
#[non_exhaustive]
pub enum ShoppingBrandsV2QueryAssets {
    Variant2(Vec<String>),
    Variant1(String),
    /// A variant not recognized by this version of the SDK, preserved verbatim.
    ///
    /// Match the specific variants first. Matching this one directly is an
    /// anti-pattern: that arm silently stops matching once a future SDK
    /// release adds the real variant.
    #[serde(untagged)]
    Unknown(serde_json::Value),
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ShoppingMerchantsV2QueryGroupBy {
    #[serde(rename = "date")]
    Date,
    #[serde(rename = "brand")]
    Brand,
    #[serde(rename = "product")]
    Product,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ShoppingMerchantsV2QueryGroupBy {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Date => "date",
            Self::Brand => "brand",
            Self::Product => "product",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ShoppingMerchantsV2QueryGroupBy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ShoppingMerchantsV2QueryGroupBy {
    fn from(value: &str) -> Self {
        match value {
            "date" => Self::Date,
            "brand" => Self::Brand,
            "product" => Self::Product,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ShoppingMerchantsV2QueryMetric {
    #[serde(rename = "merchant_share")]
    MerchantShare,
    #[serde(rename = "merchant_share_rank")]
    MerchantShareRank,
    #[serde(rename = "merchant_visibility")]
    MerchantVisibility,
    #[serde(rename = "merchant_visibility_rank")]
    MerchantVisibilityRank,
    #[serde(rename = "visibility_rank")]
    VisibilityRank,
    #[serde(rename = "brand_share")]
    BrandShare,
    #[serde(rename = "product_visibility")]
    ProductVisibility,
    #[serde(rename = "product_rank")]
    ProductRank,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ShoppingMerchantsV2QueryMetric {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::MerchantShare => "merchant_share",
            Self::MerchantShareRank => "merchant_share_rank",
            Self::MerchantVisibility => "merchant_visibility",
            Self::MerchantVisibilityRank => "merchant_visibility_rank",
            Self::VisibilityRank => "visibility_rank",
            Self::BrandShare => "brand_share",
            Self::ProductVisibility => "product_visibility",
            Self::ProductRank => "product_rank",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ShoppingMerchantsV2QueryMetric {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ShoppingMerchantsV2QueryMetric {
    fn from(value: &str) -> Self {
        match value {
            "merchant_share" => Self::MerchantShare,
            "merchant_share_rank" => Self::MerchantShareRank,
            "merchant_visibility" => Self::MerchantVisibility,
            "merchant_visibility_rank" => Self::MerchantVisibilityRank,
            "visibility_rank" => Self::VisibilityRank,
            "brand_share" => Self::BrandShare,
            "product_visibility" => Self::ProductVisibility,
            "product_rank" => Self::ProductRank,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ShoppingMerchantsV2QueryInterval {
    #[serde(rename = "day")]
    Day,
    #[serde(rename = "week")]
    Week,
    #[serde(rename = "month")]
    Month,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ShoppingMerchantsV2QueryInterval {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Day => "day",
            Self::Week => "week",
            Self::Month => "month",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ShoppingMerchantsV2QueryInterval {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ShoppingMerchantsV2QueryInterval {
    fn from(value: &str) -> Self {
        match value {
            "day" => Self::Day,
            "week" => Self::Week,
            "month" => Self::Month,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ShoppingProductsV2QueryGroupBy {
    #[serde(rename = "date")]
    Date,
    #[serde(rename = "topic")]
    Topic,
    #[serde(rename = "prompt")]
    Prompt,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ShoppingProductsV2QueryGroupBy {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Date => "date",
            Self::Topic => "topic",
            Self::Prompt => "prompt",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ShoppingProductsV2QueryGroupBy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ShoppingProductsV2QueryGroupBy {
    fn from(value: &str) -> Self {
        match value {
            "date" => Self::Date,
            "topic" => Self::Topic,
            "prompt" => Self::Prompt,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ShoppingProductsV2QueryMetric {
    #[serde(rename = "visibility_score")]
    VisibilityScore,
    #[serde(rename = "average_position")]
    AveragePosition,
    #[serde(rename = "visibility_rank")]
    VisibilityRank,
    #[serde(rename = "position1_percentage")]
    Position1Percentage,
    #[serde(rename = "position2_percentage")]
    Position2Percentage,
    #[serde(rename = "position3_percentage")]
    Position3Percentage,
    #[serde(rename = "position_above3_percentage")]
    PositionAbove3Percentage,
    #[serde(rename = "product_rating")]
    ProductRating,
    #[serde(rename = "product_num_reviews")]
    ProductNumReviews,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ShoppingProductsV2QueryMetric {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::VisibilityScore => "visibility_score",
            Self::AveragePosition => "average_position",
            Self::VisibilityRank => "visibility_rank",
            Self::Position1Percentage => "position1_percentage",
            Self::Position2Percentage => "position2_percentage",
            Self::Position3Percentage => "position3_percentage",
            Self::PositionAbove3Percentage => "position_above3_percentage",
            Self::ProductRating => "product_rating",
            Self::ProductNumReviews => "product_num_reviews",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ShoppingProductsV2QueryMetric {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ShoppingProductsV2QueryMetric {
    fn from(value: &str) -> Self {
        match value {
            "visibility_score" => Self::VisibilityScore,
            "average_position" => Self::AveragePosition,
            "visibility_rank" => Self::VisibilityRank,
            "position1_percentage" => Self::Position1Percentage,
            "position2_percentage" => Self::Position2Percentage,
            "position3_percentage" => Self::Position3Percentage,
            "position_above3_percentage" => Self::PositionAbove3Percentage,
            "product_rating" => Self::ProductRating,
            "product_num_reviews" => Self::ProductNumReviews,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ShoppingProductsV2QueryInterval {
    #[serde(rename = "day")]
    Day,
    #[serde(rename = "week")]
    Week,
    #[serde(rename = "month")]
    Month,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ShoppingProductsV2QueryInterval {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Day => "day",
            Self::Week => "week",
            Self::Month => "month",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ShoppingProductsV2QueryInterval {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ShoppingProductsV2QueryInterval {
    fn from(value: &str) -> Self {
        match value {
            "day" => Self::Day,
            "week" => Self::Week,
            "month" => Self::Month,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ShoppingTriggerRateV2QueryGroupBy {
    #[serde(rename = "date")]
    Date,
    #[serde(rename = "topic")]
    Topic,
    #[serde(rename = "region")]
    Region,
    #[serde(rename = "persona")]
    Persona,
    #[serde(rename = "prompt")]
    Prompt,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ShoppingTriggerRateV2QueryGroupBy {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Date => "date",
            Self::Topic => "topic",
            Self::Region => "region",
            Self::Persona => "persona",
            Self::Prompt => "prompt",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ShoppingTriggerRateV2QueryGroupBy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ShoppingTriggerRateV2QueryGroupBy {
    fn from(value: &str) -> Self {
        match value {
            "date" => Self::Date,
            "topic" => Self::Topic,
            "region" => Self::Region,
            "persona" => Self::Persona,
            "prompt" => Self::Prompt,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ShoppingTriggerRateV2QueryMetric {
    #[serde(rename = "total_runs")]
    TotalRuns,
    #[serde(rename = "shopping_triggered_runs")]
    ShoppingTriggeredRuns,
    #[serde(rename = "trigger_rate_percentage")]
    TriggerRatePercentage,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ShoppingTriggerRateV2QueryMetric {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::TotalRuns => "total_runs",
            Self::ShoppingTriggeredRuns => "shopping_triggered_runs",
            Self::TriggerRatePercentage => "trigger_rate_percentage",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ShoppingTriggerRateV2QueryMetric {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ShoppingTriggerRateV2QueryMetric {
    fn from(value: &str) -> Self {
        match value {
            "total_runs" => Self::TotalRuns,
            "shopping_triggered_runs" => Self::ShoppingTriggeredRuns,
            "trigger_rate_percentage" => Self::TriggerRatePercentage,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ShoppingTriggerRateV2QueryInterval {
    #[serde(rename = "day")]
    Day,
    #[serde(rename = "week")]
    Week,
    #[serde(rename = "month")]
    Month,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ShoppingTriggerRateV2QueryInterval {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Day => "day",
            Self::Week => "week",
            Self::Month => "month",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ShoppingTriggerRateV2QueryInterval {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ShoppingTriggerRateV2QueryInterval {
    fn from(value: &str) -> Self {
        match value {
            "day" => Self::Day,
            "week" => Self::Week,
            "month" => Self::Month,
            other => Self::Unknown(other.to_owned()),
        }
    }
}
