// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `volume`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

/// Single projected volume row.
///
/// Each keyword query returns both weekly and monthly rows in one response;
/// frequency distinguishes them and matches the fast table's values
/// ('Week - Monday Start' / 'Month').
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct OtfVolumeData {
    pub country_code: String,
    pub platform: String,
    pub matching_type: String,
    pub frequency: String,
    pub date: chrono::NaiveDate,
    #[serde(serialize_with = "crate::number::serialize")]
    pub volume: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct OtfVolumeRequest {
    pub keyword: String,
    pub matching_type: OtfVolumeRequestMatchingType,
    pub start_date: chrono::NaiveDate,
    pub end_date: chrono::NaiveDate,
    /// ISO 3166-1 alpha-3 country codes (e.g. USA). Omit to include every region.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub regions: Option<Vec<String>>,
    /// Platforms to restrict to. Omit to include every platform.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub platforms: Option<Vec<OtfVolumeRequestPlatform>>,
    /// Organization whose daily keyword allowance is used. Required in the JSON request body for API keys with multiple organizations that have API access. If omitted or null, defaults to the API key's sole organization with API access or the token's active organization. For OAuth/M2M tokens, any supplied organization_id must match the token's organization.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub organization_id: Option<String>,
}

impl OtfVolumeRequest {
    /// Creates a new `OtfVolumeRequest` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `OtfVolumeRequest { regions: Some(…), ..OtfVolumeRequest::new(keyword, matching_type, start_date, end_date) }`.
    pub fn new(
        keyword: impl Into<String>,
        matching_type: OtfVolumeRequestMatchingType,
        start_date: chrono::NaiveDate,
        end_date: chrono::NaiveDate,
    ) -> Self {
        Self {
            keyword: keyword.into(),
            matching_type,
            start_date,
            end_date,
            regions: None,
            platforms: None,
            organization_id: None,
        }
    }
}

/// Response wrapper with metadata and data array.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct OtfVolumeResponse {
    /// Metadata for volume query response.
    /// truncated indicates if results hit MAX_ROWS limit.
    pub info: VolumeResponseInfo,
    pub data: Vec<OtfVolumeData>,
}

/// Metadata for volume query response.
/// truncated indicates if results hit MAX_ROWS limit.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct VolumeResponseInfo {
    pub total_rows: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub truncated: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub query: Option<serde_json::Value>,
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum OtfVolumeRequestMatchingType {
    #[serde(rename = "exact_match")]
    ExactMatch,
    #[serde(rename = "phrase_match")]
    PhraseMatch,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl OtfVolumeRequestMatchingType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::ExactMatch => "exact_match",
            Self::PhraseMatch => "phrase_match",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for OtfVolumeRequestMatchingType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for OtfVolumeRequestMatchingType {
    fn from(value: &str) -> Self {
        match value {
            "exact_match" => Self::ExactMatch,
            "phrase_match" => Self::PhraseMatch,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum OtfVolumeRequestPlatform {
    #[serde(rename = "chatgpt.com")]
    ChatgptCom,
    #[serde(rename = "gemini.google.com")]
    GeminiGoogleCom,
    #[serde(rename = "perplexity.ai")]
    PerplexityAi,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl OtfVolumeRequestPlatform {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::ChatgptCom => "chatgpt.com",
            Self::GeminiGoogleCom => "gemini.google.com",
            Self::PerplexityAi => "perplexity.ai",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for OtfVolumeRequestPlatform {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for OtfVolumeRequestPlatform {
    fn from(value: &str) -> Self {
        match value {
            "chatgpt.com" => Self::ChatgptCom,
            "gemini.google.com" => Self::GeminiGoogleCom,
            "perplexity.ai" => Self::PerplexityAi,
            other => Self::Unknown(other.to_owned()),
        }
    }
}
