// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `youtube`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

/// One channel (or video category) row, optionally sliced.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct YoutubeChannelRow {
    /// Channel title when grouped by channel, or the handle when no title resolved; category name when grouped by `["video_category"]`; source type when grouped by `["source_type"]`.
    pub name: String,
    /// Channel handle without the `@`, and the identifier this API exposes. Pass it to /videos as `channel_handle`. Null for the rare channel whose handle did not resolve.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
    /// Openable channel URL. Null for video-category rows.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Leading channel's 1-based position in the full ranked set, continuing across pages; repeated across that channel's cross-tab rows rather than numbering rows.
    pub rank: i64,
    /// Period start. Present when `interval` is set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// Populated for a secondary video-category slice; with group_by `["video_category"]`, the category is returned in `name` instead. An unresolved category is returned as an empty string.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub video_category: Option<String>,
    /// Answer engine as an object `{id, name}`, present when grouped by model. The name matches `info.models`; the id is the model id the other reports accept.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<DimensionRef>,
    /// YouTube source type, present when grouped by source type, including as the second dimension of a cross-tab.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_type: Option<YoutubeChannelRowSourceType>,
    /// Citations attributed to this row.
    pub count: i64,
    /// Distinct videos of this channel that were cited.
    pub videos: i64,
    /// Share of every YouTube citation in the window (attributed and unattributed alike), or the period when `interval` is set, regardless of `source_types`. An unnarrowed complete ranking sums to slightly less than 1 because unattributed citations cannot appear in channel rows; a narrowed ranking sums to its slice's share.
    pub citation_share: f64,
}

/// Channel report metadata, including effective paging and grouping settings.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct YoutubeChannelsInfo {
    /// Distinct leading channels matching the window; this can differ from the number of rows returned.
    pub total_results: i64,
    /// Number of rows returned in `data` for this page.
    pub count: i64,
    /// Opaque cursor for the next page; null on the last page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    /// Display names of the models the report covers.
    pub models: Vec<String>,
    /// Echoed request start date (YYYY-MM-DD, ET).
    pub start_date: String,
    /// Echoed request end date (YYYY-MM-DD, ET).
    pub end_date: String,
    /// Echoed normalized filter tree, or null when no filter was sent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<serde_json::Value>,
    /// Echoed category id this report covers.
    pub category_id: String,
    /// Source types this report covers. Derived from the request, not returned rows, so a listed type may have no rows.
    pub source_types: Vec<YoutubeChannelsInfoSourceType>,
    /// Echoed request cursor; omitted on the first page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Effective page size in leading channels, not returned rows.
    pub limit: i64,
    /// Effective channel time-series interval, or null when the channel report covers the full window.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interval: Option<YoutubeChannelsInfoInterval>,
    /// Echoed dimensions that define a row. Channel reports echo `["channel"]` when group_by is omitted.
    pub group_by: Vec<String>,
}

/// Channel and category rollups.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct YoutubeChannelsQuery {
    pub category_id: String,
    /// YYYY-MM-DD, ET, inclusive
    pub start_date: String,
    /// YYYY-MM-DD, ET, inclusive
    pub end_date: String,
    /// Advanced filter tree. Prompt-level dimensions are `model`, `topic`, `region`, `prompt`, `persona`, `tag`, `analysis_type`. `channel` covers both channel cases: `in` with a list of handles selects exactly those channels, resolving each handle to its channel so a renamed channel is never returned in pieces; `contains` matches a channel's title or handle by name. Combine with `and`/`or`/`not` up to 3 deep. An exact `channel` selection must be its own `and` clause, and a `channel` leaf cannot share an `or` or `not` with a prompt-level leaf, because those compile at different stages of the query. `domain` and `page` are rejected rather than approximated: every row here is one domain, and `page` is not a video id.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<FilterNode>,
    /// Page size; default 10, max 50.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Limit results to YouTube source types: `video`, `short`, `channel`, `playlist`, or `other`. Omit to include `video`, `short`, `channel`, and `playlist`; `other` is excluded because those citations have no channel. Requests containing `other` are rejected.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_types: Option<Vec<YoutubeChannelsQuerySourceType>>,
    /// What each row represents. Empty or `["channel"]` ranks channels; `["video_category"]` ranks content categories; `["source_type"]` ranks source types; `["channel", "video_category"]`, `["channel", "source_type"]` and `["channel", "model"]` return cross-tabs — a row per channel per category, or per answer engine. `limit` counts leading channels in every case, so ten channels across nine engines is ten channels and ninety rows.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_by: Option<Vec<YoutubeChannelsQueryGroupBy>>,
    /// Return a time series instead of window totals: one row per entity per period, each carrying `date`. `citation_share` is then relative to that period, so the series is comparable across periods. Omit for window totals.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interval: Option<YoutubeChannelsQueryInterval>,
}

impl YoutubeChannelsQuery {
    /// Creates a new `YoutubeChannelsQuery` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `YoutubeChannelsQuery { filter: Some(…), ..YoutubeChannelsQuery::new(category_id, start_date, end_date) }`.
    pub fn new(category_id: impl Into<String>, start_date: impl Into<String>, end_date: impl Into<String>) -> Self {
        Self {
            category_id: category_id.into(),
            start_date: start_date.into(),
            end_date: end_date.into(),
            filter: None,
            limit: None,
            cursor: None,
            source_types: None,
            group_by: None,
            interval: None,
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct YoutubeChannelsResponse {
    /// Channel report metadata, including effective paging and grouping settings.
    pub info: YoutubeChannelsInfo,
    pub data: Vec<YoutubeChannelRow>,
}

/// How much of youtube.com the rollups can speak for.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct YoutubeCoverage {
    /// Every YouTube citation in the window.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_youtube_citations: Option<i64>,
    /// Citations that resolve to a channel, so can appear in the channel and video rankings. NOT the citation_share divisor — that is total_youtube_citations, so a complete channel ranking's shares sum to slightly less than 1.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attributed_citations: Option<i64>,
    /// Citations with no channel: search and feed URLs, deleted sources, or not yet resolved.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unattributed_citations: Option<i64>,
    /// Citations pointing at long-form videos.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub citations_video: Option<i64>,
    /// Citations pointing at Shorts.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub citations_short: Option<i64>,
    /// Citations pointing at a channel page rather than a video.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub citations_channel: Option<i64>,
    /// Citations pointing at a playlist.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub citations_playlist: Option<i64>,
    /// Search, feed, and homepage URLs. Never attributable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub citations_other: Option<i64>,
    /// Distinct channels cited.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub distinct_channels: Option<i64>,
    /// Distinct long-form videos cited.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub distinct_videos: Option<i64>,
    /// Distinct Shorts cited.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub distinct_shorts: Option<i64>,
}

/// Summary report metadata.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct YoutubeSummaryInfo {
    /// Total rows matching the query before pagination (null when not computed).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_results: Option<i64>,
    /// Number of rows returned in `data` for this page.
    pub count: i64,
    /// Opaque cursor for the next page; null on the last page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    /// Display names of the models the report covers.
    pub models: Vec<String>,
    /// Echoed request start date (YYYY-MM-DD, ET).
    pub start_date: String,
    /// Echoed request end date (YYYY-MM-DD, ET).
    pub end_date: String,
    /// Echoed normalized filter tree, or null when no filter was sent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<serde_json::Value>,
    /// Echoed category id this report covers.
    pub category_id: String,
    /// All five YouTube source types; this endpoint has no source_types request field and cannot be narrowed.
    pub source_types: Vec<YoutubeSummaryInfoSourceType>,
}

/// One object describing the window.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct YoutubeSummaryQuery {
    pub category_id: String,
    /// YYYY-MM-DD, ET, inclusive
    pub start_date: String,
    /// YYYY-MM-DD, ET, inclusive
    pub end_date: String,
    /// Advanced filter tree. Prompt-level dimensions are `model`, `topic`, `region`, `prompt`, `persona`, `tag`, `analysis_type`. `channel` covers both channel cases: `in` with a list of handles selects exactly those channels, resolving each handle to its channel so a renamed channel is never returned in pieces; `contains` matches a channel's title or handle by name. Combine with `and`/`or`/`not` up to 3 deep. An exact `channel` selection must be its own `and` clause, and a `channel` leaf cannot share an `or` or `not` with a prompt-level leaf, because those compile at different stages of the query. `domain` and `page` are rejected rather than approximated: every row here is one domain, and `page` is not a video id.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<FilterNode>,
}

impl YoutubeSummaryQuery {
    /// Creates a new `YoutubeSummaryQuery` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `YoutubeSummaryQuery { filter: Some(…), ..YoutubeSummaryQuery::new(category_id, start_date, end_date) }`.
    pub fn new(category_id: impl Into<String>, start_date: impl Into<String>, end_date: impl Into<String>) -> Self {
        Self {
            category_id: category_id.into(),
            start_date: start_date.into(),
            end_date: end_date.into(),
            filter: None,
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct YoutubeSummaryResponse {
    /// Summary report metadata.
    pub info: YoutubeSummaryInfo,
    /// How much of youtube.com the rollups can speak for.
    pub data: YoutubeCoverage,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct YoutubeVideoRow {
    /// YouTube video id, as in the watch URL.
    pub video_id: String,
    /// YouTube source type: `video`, `short`, `channel`, `playlist` or `other`.
    pub source_type: YoutubeVideoRowSourceType,
    /// Resolved title, or null when unavailable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Publishing channel title, or null when unknown.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel_title: Option<String>,
    /// Handle of the publishing channel; select it with a `channel` filter of `in`. Null when unknown.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel_handle: Option<String>,
    /// Openable video URL, or null when unavailable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Openable URL for the publishing channel, or null when unknown.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel_url: Option<String>,
    /// 1-based position in the full ranked set, continuing across pages.
    pub rank: i64,
    /// Upload date, or null when unknown.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub published_at: Option<String>,
    /// Length in seconds, or null when unknown.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_seconds: Option<i64>,
    /// YouTube content category, or null when unknown.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub video_category: Option<String>,
    /// Citations attributed to this video.
    pub count: i64,
    /// Share of every YouTube citation in the window (attributed and unattributed alike), regardless of `source_types`. Shares sum to at most 1, reaching about 1 only with `attribution="all"` and no `source_types` filter; a narrowed ranking sums to its slice's share.
    pub citation_share: f64,
}

/// Video report metadata, including effective paging and attribution settings.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct YoutubeVideosInfo {
    /// Total rows matching the query before pagination (null when not computed).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_results: Option<i64>,
    /// Number of rows returned in `data` for this page.
    pub count: i64,
    /// Opaque cursor for the next page; null on the last page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    /// Display names of the models the report covers.
    pub models: Vec<String>,
    /// Echoed request start date (YYYY-MM-DD, ET).
    pub start_date: String,
    /// Echoed request end date (YYYY-MM-DD, ET).
    pub end_date: String,
    /// Echoed normalized filter tree, or null when no filter was sent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<serde_json::Value>,
    /// Echoed category id this report covers.
    pub category_id: String,
    /// Source types this report covers. Derived from the request, not returned rows, so a listed type may have no rows.
    pub source_types: Vec<YoutubeVideosInfoSourceType>,
    /// Echoed request cursor; omitted on the first page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Effective page size applied to this paged report.
    pub limit: i64,
    /// Effective video attribution mode.
    pub attribution: YoutubeVideosInfoAttribution,
}

/// Cited videos, optionally narrowed to specific channels.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct YoutubeVideosQuery {
    pub category_id: String,
    /// YYYY-MM-DD, ET, inclusive
    pub start_date: String,
    /// YYYY-MM-DD, ET, inclusive
    pub end_date: String,
    /// Advanced filter tree. Prompt-level dimensions are `model`, `topic`, `region`, `prompt`, `persona`, `tag`, `analysis_type`. `channel` covers both channel cases: `in` with a list of handles selects exactly those channels, resolving each handle to its channel so a renamed channel is never returned in pieces; `contains` matches a channel's title or handle by name. Combine with `and`/`or`/`not` up to 3 deep. An exact `channel` selection must be its own `and` clause, and a `channel` leaf cannot share an `or` or `not` with a prompt-level leaf, because those compile at different stages of the query. `domain` and `page` are rejected rather than approximated: every row here is one domain, and `page` is not a video id.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<FilterNode>,
    /// Page size; default 10, max 50.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Limit results to YouTube source types: `video`, `short`, `channel`, `playlist`, or `other`. Omit to include `video` and `short` with the default `attribution='attributed'`; `unattributed` and `all` widen the default to all five source types. Requests containing `other` with `attribution='attributed'` are rejected.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_types: Option<Vec<YoutubeVideosQuerySourceType>>,
    /// Choose attributed citations, unattributed citations, or all citations. An unattributed row has no channel: `source_type` is `other` for a search or feed URL that names no source, and any other type is a source we have no channel for.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attribution: Option<YoutubeVideosQueryAttribution>,
}

impl YoutubeVideosQuery {
    /// Creates a new `YoutubeVideosQuery` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `YoutubeVideosQuery { filter: Some(…), ..YoutubeVideosQuery::new(category_id, start_date, end_date) }`.
    pub fn new(category_id: impl Into<String>, start_date: impl Into<String>, end_date: impl Into<String>) -> Self {
        Self {
            category_id: category_id.into(),
            start_date: start_date.into(),
            end_date: end_date.into(),
            filter: None,
            limit: None,
            cursor: None,
            source_types: None,
            attribution: None,
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct YoutubeVideosResponse {
    /// Video report metadata, including effective paging and attribution settings.
    pub info: YoutubeVideosInfo,
    pub data: Vec<YoutubeVideoRow>,
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum YoutubeChannelRowSourceType {
    #[serde(rename = "video")]
    Video,
    #[serde(rename = "short")]
    Short,
    #[serde(rename = "channel")]
    Channel,
    #[serde(rename = "playlist")]
    Playlist,
    #[serde(rename = "other")]
    Other,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl YoutubeChannelRowSourceType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Video => "video",
            Self::Short => "short",
            Self::Channel => "channel",
            Self::Playlist => "playlist",
            Self::Other => "other",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for YoutubeChannelRowSourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for YoutubeChannelRowSourceType {
    fn from(value: &str) -> Self {
        match value {
            "video" => Self::Video,
            "short" => Self::Short,
            "channel" => Self::Channel,
            "playlist" => Self::Playlist,
            "other" => Self::Other,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum YoutubeChannelsInfoSourceType {
    #[serde(rename = "video")]
    Video,
    #[serde(rename = "short")]
    Short,
    #[serde(rename = "channel")]
    Channel,
    #[serde(rename = "playlist")]
    Playlist,
    #[serde(rename = "other")]
    Other,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl YoutubeChannelsInfoSourceType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Video => "video",
            Self::Short => "short",
            Self::Channel => "channel",
            Self::Playlist => "playlist",
            Self::Other => "other",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for YoutubeChannelsInfoSourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for YoutubeChannelsInfoSourceType {
    fn from(value: &str) -> Self {
        match value {
            "video" => Self::Video,
            "short" => Self::Short,
            "channel" => Self::Channel,
            "playlist" => Self::Playlist,
            "other" => Self::Other,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum YoutubeChannelsInfoInterval {
    #[serde(rename = "day")]
    Day,
    #[serde(rename = "week")]
    Week,
    #[serde(rename = "month")]
    Month,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl YoutubeChannelsInfoInterval {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Day => "day",
            Self::Week => "week",
            Self::Month => "month",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for YoutubeChannelsInfoInterval {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for YoutubeChannelsInfoInterval {
    fn from(value: &str) -> Self {
        match value {
            "day" => Self::Day,
            "week" => Self::Week,
            "month" => Self::Month,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum YoutubeChannelsQuerySourceType {
    #[serde(rename = "video")]
    Video,
    #[serde(rename = "short")]
    Short,
    #[serde(rename = "channel")]
    Channel,
    #[serde(rename = "playlist")]
    Playlist,
    #[serde(rename = "other")]
    Other,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl YoutubeChannelsQuerySourceType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Video => "video",
            Self::Short => "short",
            Self::Channel => "channel",
            Self::Playlist => "playlist",
            Self::Other => "other",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for YoutubeChannelsQuerySourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for YoutubeChannelsQuerySourceType {
    fn from(value: &str) -> Self {
        match value {
            "video" => Self::Video,
            "short" => Self::Short,
            "channel" => Self::Channel,
            "playlist" => Self::Playlist,
            "other" => Self::Other,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum YoutubeChannelsQueryGroupBy {
    #[serde(rename = "channel")]
    Channel,
    #[serde(rename = "video_category")]
    VideoCategory,
    #[serde(rename = "model")]
    Model,
    #[serde(rename = "source_type")]
    SourceType,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl YoutubeChannelsQueryGroupBy {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Channel => "channel",
            Self::VideoCategory => "video_category",
            Self::Model => "model",
            Self::SourceType => "source_type",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for YoutubeChannelsQueryGroupBy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for YoutubeChannelsQueryGroupBy {
    fn from(value: &str) -> Self {
        match value {
            "channel" => Self::Channel,
            "video_category" => Self::VideoCategory,
            "model" => Self::Model,
            "source_type" => Self::SourceType,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum YoutubeChannelsQueryInterval {
    #[serde(rename = "day")]
    Day,
    #[serde(rename = "week")]
    Week,
    #[serde(rename = "month")]
    Month,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl YoutubeChannelsQueryInterval {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Day => "day",
            Self::Week => "week",
            Self::Month => "month",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for YoutubeChannelsQueryInterval {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for YoutubeChannelsQueryInterval {
    fn from(value: &str) -> Self {
        match value {
            "day" => Self::Day,
            "week" => Self::Week,
            "month" => Self::Month,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum YoutubeSummaryInfoSourceType {
    #[serde(rename = "video")]
    Video,
    #[serde(rename = "short")]
    Short,
    #[serde(rename = "channel")]
    Channel,
    #[serde(rename = "playlist")]
    Playlist,
    #[serde(rename = "other")]
    Other,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl YoutubeSummaryInfoSourceType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Video => "video",
            Self::Short => "short",
            Self::Channel => "channel",
            Self::Playlist => "playlist",
            Self::Other => "other",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for YoutubeSummaryInfoSourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for YoutubeSummaryInfoSourceType {
    fn from(value: &str) -> Self {
        match value {
            "video" => Self::Video,
            "short" => Self::Short,
            "channel" => Self::Channel,
            "playlist" => Self::Playlist,
            "other" => Self::Other,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum YoutubeVideoRowSourceType {
    #[serde(rename = "video")]
    Video,
    #[serde(rename = "short")]
    Short,
    #[serde(rename = "channel")]
    Channel,
    #[serde(rename = "playlist")]
    Playlist,
    #[serde(rename = "other")]
    Other,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl YoutubeVideoRowSourceType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Video => "video",
            Self::Short => "short",
            Self::Channel => "channel",
            Self::Playlist => "playlist",
            Self::Other => "other",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for YoutubeVideoRowSourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for YoutubeVideoRowSourceType {
    fn from(value: &str) -> Self {
        match value {
            "video" => Self::Video,
            "short" => Self::Short,
            "channel" => Self::Channel,
            "playlist" => Self::Playlist,
            "other" => Self::Other,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum YoutubeVideosInfoSourceType {
    #[serde(rename = "video")]
    Video,
    #[serde(rename = "short")]
    Short,
    #[serde(rename = "channel")]
    Channel,
    #[serde(rename = "playlist")]
    Playlist,
    #[serde(rename = "other")]
    Other,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl YoutubeVideosInfoSourceType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Video => "video",
            Self::Short => "short",
            Self::Channel => "channel",
            Self::Playlist => "playlist",
            Self::Other => "other",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for YoutubeVideosInfoSourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for YoutubeVideosInfoSourceType {
    fn from(value: &str) -> Self {
        match value {
            "video" => Self::Video,
            "short" => Self::Short,
            "channel" => Self::Channel,
            "playlist" => Self::Playlist,
            "other" => Self::Other,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum YoutubeVideosInfoAttribution {
    #[serde(rename = "attributed")]
    Attributed,
    #[serde(rename = "unattributed")]
    Unattributed,
    #[serde(rename = "all")]
    All,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl YoutubeVideosInfoAttribution {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Attributed => "attributed",
            Self::Unattributed => "unattributed",
            Self::All => "all",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for YoutubeVideosInfoAttribution {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for YoutubeVideosInfoAttribution {
    fn from(value: &str) -> Self {
        match value {
            "attributed" => Self::Attributed,
            "unattributed" => Self::Unattributed,
            "all" => Self::All,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum YoutubeVideosQuerySourceType {
    #[serde(rename = "video")]
    Video,
    #[serde(rename = "short")]
    Short,
    #[serde(rename = "channel")]
    Channel,
    #[serde(rename = "playlist")]
    Playlist,
    #[serde(rename = "other")]
    Other,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl YoutubeVideosQuerySourceType {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Video => "video",
            Self::Short => "short",
            Self::Channel => "channel",
            Self::Playlist => "playlist",
            Self::Other => "other",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for YoutubeVideosQuerySourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for YoutubeVideosQuerySourceType {
    fn from(value: &str) -> Self {
        match value {
            "video" => Self::Video,
            "short" => Self::Short,
            "channel" => Self::Channel,
            "playlist" => Self::Playlist,
            "other" => Self::Other,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum YoutubeVideosQueryAttribution {
    #[serde(rename = "attributed")]
    Attributed,
    #[serde(rename = "unattributed")]
    Unattributed,
    #[serde(rename = "all")]
    All,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl YoutubeVideosQueryAttribution {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Attributed => "attributed",
            Self::Unattributed => "unattributed",
            Self::All => "all",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for YoutubeVideosQueryAttribution {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for YoutubeVideosQueryAttribution {
    fn from(value: &str) -> Self {
        match value {
            "attributed" => Self::Attributed,
            "unattributed" => Self::Unattributed,
            "all" => Self::All,
            other => Self::Unknown(other.to_owned()),
        }
    }
}
